import WqoContinuousFunctions.CenteredFunctions.CenteredAsPgluing
import WqoContinuousFunctions.CenteredFunctions.FinitenessHelpers
import Mathlib.Tactic
import Mathlib.Topology.Basic
import Mathlib.SetTheory.Ordinal.Basic
import Mathlib.Order.SuccPred.Basic

open scoped Topology
open Set Function TopologicalSpace Classical

set_option autoImplicit false

noncomputable section

/-!
# Theorem 4.9 (Finitenessofcenteredfunctions) — §4.2

Relocated from `Theorems.lean` / `LocallyCentered`: consumes the §4.1
`centeredAsPgluing_iff_monotone` and the helpers in `FinitenessHelpers.lean`.
-/

/-- **Theorem 4.9 (Finitenessofcenteredfunctions).**
If `lam` is `0` or a limit ordinal and `𝒞_{[lam, lam+n]}` is generated by a finite
family `B` (i.e. `ScatFun.LevelInter lam (lam+n) ⊆ ScatFun.FinGl B`), then every
centered `g ∈ 𝒞_{[lam, lam+n+1]}` is equivalent either to the minimal function
`k_{lam+1}` (`ScatFun.minFun lam`) or to the pointed gluing `⊔ G` of some non-empty
sub-family `G = B ∘ ι` of `B`.

## Provided solution

Let `g ∈ 𝒞_{[lam, lam+n+1]}` be centered, hence of successor CB-rank by
`centeredAsPgluing_CBrank`.  In particular `g` is not equivalent to the maximal
function, so `lam < CBRank g.func ≤ lam+n+1`.

By `centeredAsPgluing_iff_monotone` there is a `≤`-monotone sequence `(gᵢ)ᵢ` with
`g ≡ ScatFun.pgl g`, where for every `i`, `CBRank (gᵢ).func < CBRank g.func ≤ lam+n+1`
and `(⨆ i, CBRank (gᵢ).func) + 1 = CBRank g.func > lam`.  In particular
`⨆ i, CBRank (gᵢ).func ≥ lam`.

* **Case `⨆ i, CBRank (gᵢ).func = lam`.**  If `lam = 0` then
  `g ≡ ScatFun.minFun 0 = ⊔ ∅`.  Otherwise `lam` is limit and
  `ScatFun.minFun lam ≡ ScatFun.pgl g ≡ g`, because `ScatFun.minFun lam` is the
  minimum at level `lam+1` (`minFun_is_minimum`) and `g` sits at that level.
  Both sub-cases land in the left disjunct `ScatFun.Equiv g (ScatFun.minFun lam hlam)`.

* **Case `⨆ i, CBRank (gᵢ).func > lam`.**  By monotonicity there is `j` with
  `CBRank (gᵢ).func ≥ lam` for all `i ≥ j`, and monotonicity again gives
  `g ≡ ScatFun.pgl_{i ≥ j} gᵢ` via two applications of `pointedGluing_upper_bound`.
  For each `i ≥ j`, since `gᵢ ∈ ScatFun.LevelInter lam (lam+n) ⊆ ScatFun.FinGl B`,
  fix a finite gluing `gᵢ ≡ ScatFun.Gl B tᵢ` and let `Gᵢ = {f ∈ B | tᵢ f > 0}`.
  Put `G = ⋃_{i ≥ j} Gᵢ`, enumerated as `B ∘ ι` (`ι : Fin k → Fin m`).  `G` is
  non-empty: otherwise every `gᵢ` (`i ≥ j`) is empty, forcing
  `⨆ i, CBRank (gᵢ).func = 0`, contradicting `> lam ≥ 0`.  By construction each
  `gᵢ ∈ ScatFun.FinGl (B ∘ ι)`, and each block of `G` reduces cofinally into
  `(gᵢ)ᵢ` by monotonicity, so `finitegenerationAndPgluing_upper` /
  `finitegenerationAndPgluing_lower` give `g ≡ ScatFun.pgl (ScatFun.repSeq (B ∘ ι))`. -/
theorem finitenessOfCenteredFunctions
    {lam : Ordinal.{0}} (hlam : lam < omega1)
    (hlim : Order.IsSuccLimit lam ∨ lam = 0)
    {m n : ℕ} (B : Fin m → ScatFun)
    (hgen : ScatFun.LevelInter lam (lam + ↑n) ⊆ ScatFun.FinGl B)
    (g : ScatFun)
    (hg_lvl  : g ∈ ScatFun.LevelInter lam (lam + ↑n + 1))
    (hg_cent : IsCentered g.func) :
    ScatFun.Equiv g (ScatFun.minFun lam hlam) ∨
      ∃ (k : ℕ) (ι : Fin k → Fin m), 0 < k ∧
        ScatFun.Equiv g (ScatFun.pgl (ScatFun.repSeq (B ∘ ι))) := by
  -- Transitivity / symmetry helpers for `ScatFun.Equiv`.
  have etrans : ∀ {a b c : ScatFun}, ScatFun.Equiv a b → ScatFun.Equiv b c → ScatFun.Equiv a c :=
    fun h h' => ⟨ContinuouslyReduces.trans h.1 h'.1, ContinuouslyReduces.trans h'.2 h.2⟩
  have esymm : ∀ {a b : ScatFun}, ScatFun.Equiv a b → ScatFun.Equiv b a :=
    fun h => ⟨h.2, h.1⟩
  -- A monotone sequence whose pointed gluing is equivalent to `g`.
  obtain ⟨s, hs_mono, hequiv⟩ := (centeredAsPgluing_iff_monotone g).1 hg_cent
  have hgequiv : ScatFun.Equiv g (ScatFun.pgl s) := hequiv
  have hs_reg : Preorder.IsRegularSeq ScatFun.Reduces s := IsMonotoneSeq.isRegularSeq s hs_mono
  have hrank : CBRank g.func = Order.succ (⨆ i, CBRank (s i).func) := by
    rw [cbRank_eq_of_equiv hgequiv, cbRank_pgl_regular s hs_reg]
  have hbdd : BddAbove (Set.range fun i => CBRank (s i).func) := by
    refine ⟨CBRank (ScatFun.pgl s).func, ?_⟩
    rintro _ ⟨i, rfl⟩
    exact ContinuouslyReduces.rank_monotone (s i).hScat (ScatFun.pgl s).hScat
      (block_reduces_pgl s i)
  set β := ⨆ i, CBRank (s i).func with hβdef
  have hsi_le_β : ∀ i, CBRank (s i).func ≤ β := fun i => le_ciSup hbdd i
  have hcb_mono : ∀ a b : ℕ, a ≤ b → CBRank (s a).func ≤ CBRank (s b).func :=
    fun a b hab => ContinuouslyReduces.rank_monotone (s a).hScat (s b).hScat (hs_mono a b hab)
  obtain ⟨hge, hle⟩ := hg_lvl
  have hβ_le : β ≤ lam + ↑n := by
    have h1 : Order.succ β ≤ lam + ↑n + 1 := hrank ▸ hle
    rw [Ordinal.add_one_eq_succ] at h1
    exact Order.succ_le_succ_iff.mp h1
  rcases eq_or_ne lam 0 with hlam0 | hlamne
  · -- `lam = 0`: every block lies in `FinGl B`.
    subst hlam0
    have hmem : ∀ i, s i ∈ ScatFun.FinGl B := fun i =>
      hgen ⟨zero_le _, le_trans (hsi_le_β i) hβ_le⟩
    choose mult hmult1 hmult2 using hmem
    have ht_eq : ∀ i, ScatFun.Equiv (s i) (ScatFun.Gl B (mult i)) :=
      fun i => ⟨hmult2 i, hmult1 i⟩
    by_cases hS : ∃ i f, 0 < mult i f
    · obtain ⟨k, ι, hk, hpgl⟩ := pgl_finGl_to_subfamily B s hs_mono mult ht_eq hS
      exact Or.inr ⟨k, ι, hk, etrans hgequiv hpgl⟩
    · push_neg at hS
      have hempty : ∀ i, IsEmpty ↥(s i).domain := by
        intro i
        have hm0 : mult i = 0 := funext fun f => Nat.le_zero.mp (hS i f)
        have hred : ScatFun.Reduces (s i) (ScatFun.Gl B (mult i)) := hmult2 i
        rw [hm0] at hred
        have hGl_empty : IsEmpty ↥(ScatFun.Gl B (0 : Fin m → ℕ)).domain := Gl_zero_isEmpty B
        obtain ⟨σ, _, _⟩ := hred
        exact ⟨fun z => hGl_empty.elim (σ z)⟩
      exact Or.inl (etrans hgequiv (pgl_allEmpty_equiv_minFun_zero s hempty hlam))
  · -- `lam` is a (nonzero) limit.
    have hlim' : Order.IsSuccLimit lam := hlim.resolve_right hlamne
    by_cases hP : ∃ i, lam ≤ CBRank (s i).func
    · -- Pointed-gluing case: use the tail from the first block of rank `≥ lam`.
      obtain ⟨i0, hi0⟩ := hP
      set t := fun i => s (i + i0) with htdef
      have ht_mono : IsMonotoneSeq t := fun a b hab => hs_mono _ _ (by omega)
      have ht_mem : ∀ i, t i ∈ ScatFun.FinGl B := by
        intro i
        refine hgen ⟨le_trans hi0 (hcb_mono i0 (i + i0) (by omega)), ?_⟩
        exact le_trans (hsi_le_β _) hβ_le
      choose mult hmult1 hmult2 using ht_mem
      have ht_eq : ∀ i, ScatFun.Equiv (t i) (ScatFun.Gl B (mult i)) :=
        fun i => ⟨hmult2 i, hmult1 i⟩
      have hS : ∃ i f, 0 < mult i f := by
        by_contra hcon
        push_neg at hcon
        have hm0 : mult 0 = 0 := funext fun f => Nat.le_zero.mp (hcon 0 f)
        -- `t 0` would be empty, so its CB-rank is `0`, contradicting `lam ≤ CBRank (t 0)`.
        have ht0_eq : t 0 = s i0 := by simp [htdef]
        have hrank_t0 : lam ≤ CBRank (t 0).func := by rw [ht0_eq]; exact hi0
        have hGl_empty : IsEmpty ↥(ScatFun.Gl B (mult 0)).domain := by
          rw [hm0]; exact Gl_zero_isEmpty B
        have ht0_empty : IsEmpty ↥(t 0).domain := by
          obtain ⟨σ, _, _⟩ := (ht_eq 0).1
          exact ⟨fun z => hGl_empty.elim (σ z)⟩
        have hrank0 : CBRank (t 0).func = 0 := by
          have h0 : CBLevel (t 0).func 0 = ∅ := by
            rw [CBLevel_zero]; exact Set.eq_empty_of_isEmpty _
          exact le_antisymm (CBRank_le_of_CBLevel_empty _ _ h0) (zero_le _)
        rw [hrank0] at hrank_t0
        exact hlamne (le_antisymm hrank_t0 (zero_le _))
      obtain ⟨k, ι, hk, hpgl⟩ := pgl_finGl_to_subfamily B t ht_mono mult ht_eq hS
      refine Or.inr ⟨k, ι, hk, ?_⟩
      exact etrans hgequiv (etrans (esymm (pgl_tail_equiv s hs_mono i0)) hpgl)
    · -- Minimum-function case: every block has rank `< lam`, so `g ≡ k_{lam+1}`.
      push_neg at hP
      have hβ_ge : lam ≤ β := by
        by_contra hlt
        push_neg at hlt
        exact absurd (hrank ▸ hge) (not_le.mpr (hlim'.succ_lt hlt))
      have hβ_eq : β = lam := le_antisymm (ciSup_le' fun i => (hP i).le) hβ_ge
      -- `minFun lam ≤ g`.
      have hCBne : (CBLevel g.func lam).Nonempty :=
        CBLevel_nonempty_below_rank g.func g.hScat lam (by rw [hrank, hβ_eq]; exact Order.lt_succ lam)
      have hmin_le : ScatFun.Reduces (ScatFun.minFun lam hlam) g :=
        minFun_is_minimum lam hlam g.domain g.func g.hCont g.hScat hCBne
      -- `g ≤ minFun lam`.
      have hg_le : ScatFun.Reduces g (ScatFun.minFun lam hlam) := by
        have h1 : ScatFun.Reduces (ScatFun.pgl s)
            (ScatFun.pgl (fun nn => ScatFun.minFun (cofinalSeq lam nn)
              (lt_trans (cofinalSeq_lt lam hlim' hlamne nn) hlam))) :=
          pgl_reduces_pgl s _ (fun i j₀ =>
            reduces_minFun_cofinal lam hlam hlim' hlamne (s i) (hP i) j₀)
        have h2 := (minFun_limit_equiv_pgl lam hlam hlim' hlamne).2
        exact ContinuouslyReduces.trans hgequiv.1 (ContinuouslyReduces.trans h1 h2)
      exact Or.inl ⟨hg_le, hmin_le⟩

/-! ## Corollary 4.10 (centeredSuccessor) — the limit case -/

/-- The `repSeq` of a sub-family of the one-element family `![ℓ_lam]` is the
constant sequence `ℓ_lam`: every reindex `ι : Fin k → Fin 1` is constantly `0`, so
each block is `ℓ_lam`.  Hence `pgl (repSeq (![ℓ_lam] ∘ ι)) = pgl (fun _ => ℓ_lam)
= succMaxFun lam`. -/
lemma repSeq_const_maxFun (lam : Ordinal.{0}) (hlam : lam < omega1) {k : ℕ}
    (hk : 0 < k) (ι : Fin k → Fin 1) :
    ScatFun.repSeq (![ScatFun.maxFun lam hlam] ∘ ι) = fun _ => ScatFun.maxFun lam hlam := by
  funext j
  simp only [ScatFun.repSeq, dif_pos hk, Function.comp_apply, Matrix.cons_val_fin_one]

/-! ### Corollary 4.10 — the `lam = 1` case (base of the induction)

The `lam = 1` case applies `finitenessOfCenteredFunctions` with `lam = 0`, `n = 1` and
the two generators `genLeOne = ![k₁, ℓ₁]` of `𝒞_{≤1}` (finite generation supplied by
`cLeOne_finitely_generated`).  The non-minimal disjunct is a `pgl` of a non-empty
sub-family of `{k₁, ℓ₁}`, which is `≡ pgl ℓ₁ = succMaxFun 1` when `ℓ₁` occurs
(since `k₁ ≤ ℓ₁`) and `≡ k₂ = minFun 1` when only `k₁` occurs. -/

/-- `k₁ ≤ ℓ₁`: the minimum function `MinFun 0` reduces to `MaxFun 1` (rank `1 ≥ 1`,
so `CBLevel · 0 = univ` is non-empty — it contains `prepend 0 0^ω`). -/
lemma minFun_zero_le_maxFun_one :
    ContinuouslyReduces (MinFun 0) (MaxFun 1) := by
  apply minFun_is_minimum 0 zero_lt_omega1 (MaxDom 1) (MaxFun 1)
    (ScatFun.maxFun 1 one_lt_omega1).hCont (ScatFun.maxFun 1 one_lt_omega1).hScat
  rw [CBLevel_zero]
  refine ⟨⟨prepend 0 zeroStream, ?_⟩, trivial⟩
  rw [show (1 : Ordinal) = Order.succ 0 from by rw [← Ordinal.add_one_eq_succ, zero_add],
    MaxDom_succ]
  exact mem_gluingSet_prepend (zeroStream_mem_pointedGluingSet _)

open ScatFun in
/-- `pgl (fun _ => k₁) ≡ k₂`: the pointed gluing of `ω` copies of `k₁ = minFun 0` is the
minimum function `k₂ = minFun 1`.  (`minFun 1` is the minimum at rank `≥ 2`, and
`pgl (const k₁)` has CB-rank `2`; conversely its underlying function is literally the
value map on `MinDom 1 = PointedGluingSet (fun _ => MinDom 0)`.) -/
lemma pgl_const_minFun_zero_equiv_minFun_one :
    ScatFun.Equiv (ScatFun.pgl (fun _ => ScatFun.minFun 0 zero_lt_omega1))
      (ScatFun.minFun 1 one_lt_omega1) := by
  have hrank : (1 : Ordinal) <
      CBRank (ScatFun.pgl (fun _ => ScatFun.minFun 0 zero_lt_omega1)).func := by
    rw [cbRank_pgl_regular _ (scatFun_const_isRegularSeq _), ciSup_const,
      minFun_cbRank_eq 0 zero_lt_omega1,
      show (1 : Ordinal) = Order.succ 0 from by rw [← Ordinal.add_one_eq_succ, zero_add]]
    exact Order.lt_succ _
  constructor
  · -- `pgl (const k₁) ≤ k₂`, via the value-map identification of the domains.
    refine ⟨fun z => ⟨z.val, ?_⟩, ?_, id, continuousOn_id, ?_⟩
    · show z.val ∈ MinDom 1
      have hdeq : MinDom (1 : Ordinal) = PointedGluingSet (fun _ => MinDom 0) := by
        rw [show (1 : Ordinal) = Order.succ 0 from by rw [← Ordinal.add_one_eq_succ, zero_add]]
        exact MinDom_succ 0
      rw [hdeq]
      exact z.prop
    · exact Continuous.subtype_mk continuous_subtype_val _
    · intro z
      exact scatFun_pgl_func_eq_val (fun _ => ScatFun.minFun 0 zero_lt_omega1)
        (fun _ a => rfl) z
  · -- `k₂ ≤ pgl (const k₁)`: minimality (rank `pgl = 2 > 1`).
    exact minFun_is_minimum 1 one_lt_omega1 _ _
      (ScatFun.pgl _).hCont (ScatFun.pgl _).hScat
      (CBLevel_nonempty_below_rank _ (ScatFun.pgl _).hScat 1 hrank)

open ScatFun in
/-- A sub-family of `genLeOne = ![k₁, ℓ₁]` that omits `ℓ₁` (`∀ j, ι j = 0`) has
`repSeq` constantly `k₁`. -/
lemma repSeq_genLeOne_const_minFun {k : ℕ} (hk : 0 < k) (ι : Fin k → Fin 2)
    (h0 : ∀ j, ι j = 0) :
    ScatFun.repSeq (genLeOne ∘ ι) = fun _ => ScatFun.minFun 0 zero_lt_omega1 := by
  funext j
  simp only [ScatFun.repSeq, dif_pos hk, Function.comp_apply, h0, genLeOne,
    Matrix.cons_val_zero]

open ScatFun in
/-- A sub-family of `genLeOne = ![k₁, ℓ₁]` that contains `ℓ₁` (`∃ p, ι p = 1`) has
`pgl (repSeq (genLeOne ∘ ι)) ≡ pgl ℓ₁ = succMaxFun 1`: every block reduces to `ℓ₁`
(using `k₁ ≤ ℓ₁`), and `ℓ₁` occurs cofinally in `repSeq`. -/
lemma pgl_genLeOne_with_one {k : ℕ} (hk : 0 < k) (ι : Fin k → Fin 2)
    (h1 : ∃ p, ι p = 1) :
    ScatFun.Equiv (ScatFun.pgl (ScatFun.repSeq (genLeOne ∘ ι)))
      (ScatFun.succMaxFun 1 one_lt_omega1) := by
  obtain ⟨p, hp⟩ := h1
  show ScatFun.Equiv _ (ScatFun.pgl (fun _ => ScatFun.maxFun 1 one_lt_omega1))
  -- Each `repSeq` block is `k₁` or `ℓ₁`.
  have hblock : ∀ i, ScatFun.repSeq (genLeOne ∘ ι) i = ScatFun.minFun 0 zero_lt_omega1
      ∨ ScatFun.repSeq (genLeOne ∘ ι) i = ScatFun.maxFun 1 one_lt_omega1 := by
    intro i
    have hi : ι ⟨i % k, Nat.mod_lt i hk⟩ = 0 ∨ ι ⟨i % k, Nat.mod_lt i hk⟩ = 1 := by omega
    simp only [ScatFun.repSeq, dif_pos hk, Function.comp_apply]
    rcases hi with h | h <;> rw [h] <;> simp [genLeOne]
  constructor
  · -- `≤`: every block reduces to `ℓ₁`.
    apply pgl_reduces_pgl
    intro i j₀
    refine ⟨j₀, le_refl _, ?_⟩
    rcases hblock i with h | h <;> rw [h]
    · exact minFun_zero_le_maxFun_one
    · exact ContinuouslyReduces.refl _
  · -- `≥`: `ℓ₁` occurs at every index `≡ p (mod k)`, cofinally.
    apply pgl_reduces_pgl
    intro i j₀
    refine ⟨(p : ℕ) + k * (j₀ + 1), ?_, ?_⟩
    · -- `j₀ ≤ p + k * (j₀ + 1)`, using `k ≥ 1`.
      have hk' : k = (k - 1) + 1 := by omega
      have hexp : k * (j₀ + 1) = (j₀ + 1) + (k - 1) * (j₀ + 1) := by
        conv_lhs => rw [hk']
        ring
      omega
    · have hmod : ((p : ℕ) + k * (j₀ + 1)) % k = (p : ℕ) := by
        rw [Nat.add_mul_mod_self_left]; exact Nat.mod_eq_of_lt p.is_lt
      simp only [ScatFun.repSeq, dif_pos hk, Function.comp_apply]
      rw [show (⟨((p : ℕ) + k * (j₀ + 1)) % k, Nat.mod_lt _ hk⟩ : Fin k) = p from Fin.ext hmod, hp]
      simp only [genLeOne, Matrix.cons_val_one]
      exact ContinuouslyReduces.refl _

open ScatFun in
/-- **Corollary 4.10 (centeredSuccessor) — dichotomy.**
For `lam` equal to `1` or a *nonzero limit* ordinal `< ω₁`, every centered scattered
continuous function `g` of CB-rank `lam + 1` is continuously equivalent either to the
minimum function `k_{lam+1}` (`minFun lam`) or to `pgl ℓ_lam` (`succMaxFun lam`).

* **`lam` limit:** specialise `finitenessOfCenteredFunctions` (Theorem 4.9) to the
  one-element generating family `![ℓ_lam]` (`n = 0`), discharging finite generation by
  `limit_rank_equiv_maxFun`; the non-minimal disjunct is `pgl ℓ_lam = succMaxFun lam`
  (`repSeq_const_maxFun`).
* **`lam = 1`:** specialise Theorem 4.9 to `lam = 0`, `n = 1`,
  `B = genLeOne = ![k₁, ℓ₁]` (finite generation of `𝒞_{≤1}` from
  `cLeOne_finitely_generated`).  The minimal disjunct `≡ k₁` is impossible by rank
  (`CBRank g = 2 ≠ 1`); the non-minimal disjunct — a `pgl` of a non-empty sub-family of
  `{k₁, ℓ₁}` — is `≡ succMaxFun 1` if `ℓ₁` occurs (`pgl_genLeOne_with_one`) and
  `≡ minFun 1` otherwise (`repSeq_genLeOne_const_minFun` +
  `pgl_const_minFun_zero_equiv_minFun_one`). -/
theorem centeredSuccessor (lam : Ordinal.{0}) (hlam_lt : lam < omega1)
    (hlam_cases : lam = 1 ∨ (Order.IsSuccLimit lam ∧ lam ≠ 0))
    (g : ScatFun) (hg_rank : CBRank g.func = lam + 1)
    (hg_cent : IsCentered g.func) :
    ScatFun.Equiv g (ScatFun.minFun lam hlam_lt) ∨
      ScatFun.Equiv g (ScatFun.succMaxFun lam hlam_lt) := by
  rcases hlam_cases with rfl | ⟨hlim, hlam_ne⟩
  · -- `lam = 1`: Theorem 4.9 with `lam = 0`, `n = 1`, `B = genLeOne`.
    have hgen : ScatFun.LevelInter 0 (0 + ↑(1 : ℕ)) ⊆ ScatFun.FinGl genLeOne := by
      have h01 : (0 : Ordinal) + ↑(1 : ℕ) = 1 := by simp
      rw [h01]; exact cLeOne_finitely_generated
    have hg_lvl : g ∈ ScatFun.LevelInter 0 (0 + ↑(1 : ℕ) + 1) :=
      ⟨zero_le _, by rw [hg_rank]; simp⟩
    rcases finitenessOfCenteredFunctions zero_lt_omega1 (Or.inr rfl) genLeOne hgen g hg_lvl
        hg_cent with hmin | ⟨k, ι, hk, hpgl⟩
    · -- minimal disjunct `≡ k₁` is impossible: `CBRank g = 2 ≠ 1`.
      exfalso
      have hc := cbRank_eq_of_equiv hmin
      have h2 : CBRank (ScatFun.minFun 0 zero_lt_omega1).func = 1 := by
        rw [minFun_cbRank_eq 0 zero_lt_omega1, ← Ordinal.add_one_eq_succ, zero_add]
      rw [hg_rank, h2] at hc
      have hlt : (1 : Ordinal) < 1 + 1 := by rw [Ordinal.add_one_eq_succ]; exact Order.lt_succ _
      exact absurd hc (ne_of_lt hlt).symm
    · by_cases h1 : ∃ p, ι p = 1
      · -- `ℓ₁` occurs: `g ≡ succMaxFun 1`.
        have h := pgl_genLeOne_with_one hk ι h1
        exact Or.inr ⟨hpgl.1.trans h.1, h.2.trans hpgl.2⟩
      · -- only `k₁` occurs: `g ≡ minFun 1`.
        push_neg at h1
        have h0 : ∀ j, ι j = 0 := fun j => by have := h1 j; omega
        rw [repSeq_genLeOne_const_minFun hk ι h0] at hpgl
        exact Or.inl ⟨hpgl.1.trans pgl_const_minFun_zero_equiv_minFun_one.1,
          pgl_const_minFun_zero_equiv_minFun_one.2.trans hpgl.2⟩
  · -- `lam` a nonzero limit: the original proof (single generator `ℓ_lam`, `n = 0`).
    have hgen : ScatFun.LevelInter lam (lam + ↑(0 : ℕ)) ⊆
        ScatFun.FinGl ![ScatFun.maxFun lam hlam_lt] := by
      intro F hF
      have hrankF : CBRank F.func = lam := le_antisymm (by simpa using hF.2) hF.1
      have hFeq : ScatFun.Equiv F (ScatFun.maxFun lam hlam_lt) :=
        limit_rank_equiv_maxFun F lam hlam_lt hlim hrankF
      exact finGl_closed_equiv _ (single_mem_finGl (ScatFun.maxFun lam hlam_lt))
        ⟨hFeq.2, hFeq.1⟩
    have hg_lvl : g ∈ ScatFun.LevelInter lam (lam + ↑(0 : ℕ) + 1) := by
      refine ⟨?_, ?_⟩
      · rw [hg_rank, Ordinal.add_one_eq_succ]; exact Order.le_succ lam
      · simp [hg_rank]
    rcases finitenessOfCenteredFunctions hlam_lt (Or.inl hlim) ![ScatFun.maxFun lam hlam_lt]
        hgen g hg_lvl hg_cent with hmin | ⟨k, ι, hk, hpgl⟩
    · exact Or.inl hmin
    · refine Or.inr ?_
      rw [repSeq_const_maxFun lam hlam_lt hk ι] at hpgl
      exact hpgl

end
