import WqoContinuousFunctions.ScatFun.Generators.Defs
import WqoContinuousFunctions.PointedGluing.MaxFun.Maximum
import WqoContinuousFunctions.PointedGluing.GeneralStructure
import WqoContinuousFunctions.PointedGluing.Basics.Properties
import WqoContinuousFunctions.ScatFun.PreciseStructure.IntertwineOmegaCentered
import WqoContinuousFunctions.CenteredFunctions.FinitenessHelpers
import WqoContinuousFunctions.ContinuousReducibility.Gluing.LocallyConstant
import WqoContinuousFunctions.ScatFun.LevelsFinitelyGenerated.GlList

open scoped Topology
open Set Function TopologicalSpace Classical

set_option autoImplicit false

noncomputable section

/-!
# Finite generation of `CB`-rank levels (memoir `PreciseStructureThm`)

`ScatFun.levels_finitely_generated` is the memoir's goal statement for chapter 5: every
`ScatFun` of `CB`-rank `α` is a finite gluing of elements of `Generators α`.


This file also collects the level-by-level instances that are provable directly from existing
`PointedGluing` results, without needing the (assembled but not yet fully proved)
inductive machinery of `Centered`/`Generators` at successor-of-successor levels:

* `Generators_zero_finitely_generates` — level `0` (the only function is `ScatFun.empty`,
  `Generators 0 = ∅`).
* `Generators_lambda_finitely_generates` — every limit level `λ` (`Generators λ = {ℓ_λ}`, and
  `ℓ_λ` is both an upper *and* (at a limit) a lower bound for `CB`-rank `λ`).

`Generators_one_finitely_generates` (level `1`, `𝒢_1 = {k_1, ω k_1}`) is deferred: the memoir
notes "`FG(1)` amounts to `LocallyConstantFunctions`"
(`5_precise_struct_memo.tex:534`), i.e. it needs the characterisation of `CB`-rank-`1`
functions as (finite gluings of) locally constant functions, which is a real piece of work in
its own right — not attempted here.
-/

namespace ScatFun

/-- **Level `0` is finitely generated by `𝒢_0 = ∅`.**  The only `ScatFun` of `CB`-rank `0` is
(up to the vacuous empty-domain reduction) `ScatFun.empty`, matching the memoir's remark that
`𝒢_0 = ∅` generates "the only function of null `CB`-rank, namely the empty function"
(`5_precise_struct_memo.tex:454`). -/
theorem Generators_zero_finitely_generates :
    ∀ F : ScatFun, CBRank F.func = 0 → F ∈ FinGl (Generators 0).toFinFun := by
  intro F hF
  have hIsEmpty : IsEmpty ↥F.domain := by
    by_contra h
    rw [not_isEmpty_iff] at h
    exact absurd hF (ne_of_gt (CBRank_pos_of_scattered_nonempty F.func F.hScat h))
  exact empty_mem_FinGl _ hIsEmpty

/-- **Every limit level `λ` is finitely generated by `𝒢_λ = {ℓ_λ}`.**  Uses
`maxFun_is_maximum` (`ℓ_λ` is an upper bound for `CB`-rank `≤ λ`) and `MaxFun_le_limit_rank`
(at a *limit* `λ`, `ℓ_λ` is also a lower bound for `CB`-rank exactly `λ`) to get `F ≡ ℓ_λ`
whenever `CBRank F.func = λ`; then `F ≡ ℓ_λ` transfers along `ℓ_λ ≡ glList [ℓ_λ] = Gl ![ℓ_λ] ![1]`
(`glList_single_equiv`) to membership in `FinGl (Generators λ).toFinFun`. -/
theorem Generators_lambda_finitely_generates (lam : Ordinal.{0}) (hlim : Order.IsSuccLimit lam)
    (hlam : lam < omega1) :
    ∀ F : ScatFun, CBRank F.func = lam → F ∈ FinGl (Generators lam).toFinFun := by
  intro F hF
  have hGen : Generators lam = {maxFun lam hlam} := by
    have hzero : lam.natPart = 0 := by
      have heq : lam = lam + ((0 : ℕ) : Ordinal.{0}) := by simp
      conv_lhs => rw [heq]
      exact Ordinal.natPart_add_natCast lam 0 (Or.inl hlim)
    have hlimitPart : lam.limitPart = lam := by
      have heq : lam = lam + ((0 : ℕ) : Ordinal.{0}) := by simp
      conv_lhs => rw [heq]
      exact Ordinal.limitPart_add_natCast lam 0 (Or.inl hlim)
    simp only [Generators, GenBlock, genBase, hzero, hlimitPart]
    rw [if_neg (show lam ≠ 0 from by simpa using hlim.ne_bot), dif_pos hlam]
  have hEquiv : Equiv F (maxFun lam hlam) := by
    have hf_le : ContinuouslyReduces F.func (maxFun lam hlam).func := by
      rw [maxFun_func]
      refine' (maxFun_is_maximum lam hlam).1 F.func F.hCont F.hScat (fun β hβ => _)
      exact Set.eq_empty_of_subset_empty
        ((CBLevel_eq_empty_at_rank F.func F.hScat) ▸ CBLevel_antitone F.func (hF ▸ hβ))
    have hf_ge : ContinuouslyReduces (maxFun lam hlam).func F.func := by
      rw [maxFun_func]
      exact MaxFun_le_limit_rank lam hlam hlim F.domain F.func F.hCont F.hScat hF
    exact ⟨hf_le, hf_ge⟩
  have hGl : Equiv F (glList [maxFun lam hlam]) := ⟨hEquiv.1.trans (glList_single_equiv _).1,
    (glList_single_equiv _).2.trans hEquiv.2⟩
  rw [hGen]
  have hB0 : ∀ j : Fin ({maxFun lam hlam} : Finset ScatFun).card,
      ({maxFun lam hlam} : Finset ScatFun).toFinFun j = maxFun lam hlam := by
    intro j
    have hl : ({maxFun lam hlam} : Finset ScatFun).toList = [maxFun lam hlam] :=
      Finset.toList_singleton _
    simp only [Finset.toFinFun]
    rw [List.get_eq_getElem]
    have hjv : j.val = 0 := by
      have hc : ({maxFun lam hlam} : Finset ScatFun).card = 1 := Finset.card_singleton _
      have := j.isLt
      omega
    simp only [Fin.val_cast, hjv]
    simp [hl]
  have hflat : ∀ (n : ℕ) (w : ScatFun),
      (List.finRange n).flatMap (fun _ : Fin n => [w]) = List.replicate n w := by
    intro n w
    induction n with
    | zero => simp
    | succ k ih =>
      rw [List.finRange_succ, List.flatMap_cons, List.flatMap_map, List.replicate_succ]
      simpa using ih
  have hGleq : Gl ({maxFun lam hlam} : Finset ScatFun).toFinFun (fun _ => 1)
      = glList [maxFun lam hlam] := by
    have hcl : copiesList ({maxFun lam hlam} : Finset ScatFun).toFinFun (fun _ => 1)
        = [maxFun lam hlam] := by
      unfold copiesList
      rw [show (fun i : Fin ({maxFun lam hlam} : Finset ScatFun).card =>
            List.replicate ((fun _ : Fin ({maxFun lam hlam} : Finset ScatFun).card => (1:ℕ)) i)
              (({maxFun lam hlam} : Finset ScatFun).toFinFun i))
          = (fun i => [maxFun lam hlam]) from funext (fun i => by rw [hB0 i, List.replicate_one])]
      rw [hflat, Finset.card_singleton, List.replicate_one]
    unfold Gl glList copiesSeq
    rw [hcl]
  refine ⟨fun _ => 1, ?_, ?_⟩
  · rw [hGleq]; exact hGl.2
  · rw [hGleq]; exact hGl.1

/-- **`𝒢_1 = {k_1, ω k_1}`**, per `AlreadyKnownGenerators` item 1
(`5_precise_struct_memo.tex:458`): unfolding the block recursion at `λ = 0`, `n = 1`,
`genStep` reduces to `C1 ∪ ω{C1}` (the wedge-generator term vanishes since `Gen 0 = ∅` makes
`nonemptySubsets (nonemptySubsets ∅) = ∅`). -/
lemma Generators_one_eq (h : (0 : Ordinal.{0}) < omega1) :
    Generators 1 = {minFun 0 h, omega (minFun 0 h)} := by
  simp only [Generators, limitPart_one, natPart_one, GenBlock, genBase, centBase1, if_true,
    dif_pos h]
  simp only [genStep, CentBlock, nonemptySubsets, Finset.powerset_empty,
    Finset.erase_singleton, Finset.biUnion_empty, Finset.empty_union, Finset.union_empty,
    omegaImage, Finset.image_singleton]
  rfl

/-- `k_1 = minFun 0 h` has domain `{0^ω}` (`minFun_zero_domain`), so `ω k_1 = gl (fun _ => k_1)`
has domain exactly `⋃ i, {prepend i 0^ω}`: every point `x` in it is forced (via
`GluingSet_inverse_short` + `minFun_zero_domain`) to equal `prepend (x.val 0) 0^ω`. -/
lemma omega_minFun_zero_point (h : (0 : Ordinal.{0}) < omega1)
    (x : ↥(omega (minFun 0 h)).domain) : x.val = prepend (x.val 0) zeroStream := by
  have hx' : x.val ∈ GluingSet (fun _ : ℕ => (minFun 0 h).domain) := x.prop
  obtain ⟨j, hj0, hjmem⟩ := GluingSet_inverse_short (fun _ : ℕ => (minFun 0 h).domain) ⟨x.val, hx'⟩
  have hjmem2 : unprepend x.val ∈ (minFun 0 h).domain := hjmem
  rw [minFun_zero_domain, Set.mem_singleton_iff] at hjmem2
  conv_lhs => rw [← prepend_unprepend x.val]
  rw [hjmem2]

/-- `ω k_1` acts as the identity on the (first-coordinate) label of its points. -/
lemma omega_minFun_zero_func_eq (h : (0 : Ordinal.{0}) < omega1)
    (x : ↥(omega (minFun 0 h)).domain) : (omega (minFun 0 h)).func x = x.val := by
  have hxval := omega_minFun_zero_point h x
  have hxmem : (minFun 0 h).func ⟨zeroStream, minFun_zero_domain ▸ rfl⟩ = zeroStream := rfl
  have := omega_func_prepend (minFun 0 h) (x.val 0) ⟨zeroStream, minFun_zero_domain ▸ rfl⟩
  rw [hxmem] at this
  have hxx : x = ⟨prepend (x.val 0) zeroStream,
      mem_gluingSet_prepend (minFun_zero_domain ▸ rfl)⟩ := Subtype.ext hxval
  rw [hxx]; exact this

/-- **`ω k_1 ≡ id_ℕ`.**  Locally constant (every point is isolated, via the first-coordinate
clopen blocks and `omega_minFun_zero_point` forcing each block to be a singleton) with infinite
image (`omega_minFun_zero_func_eq` identifies the image with the domain, which biject with `ℕ`
via `prepend · zeroStream`). Mirrors `maxFun_one_equiv_id`. -/
lemma omega_minFun_zero_equiv_id (h : (0 : Ordinal.{0}) < omega1) :
    ContinuouslyEquiv (omega (minFun 0 h)).func (@id ℕ) := by
  have hlc : IsLocallyConstant (omega (minFun 0 h)).func := by
    rw [IsLocallyConstant.iff_exists_open]
    intro x
    refine ⟨{y : ↥(omega (minFun 0 h)).domain | y.val 0 = x.val 0},
      (isClopen_preimage_zero (x.val 0)).isOpen.preimage continuous_subtype_val, rfl, ?_⟩
    intro y hy
    have : y.val = x.val := by
      rw [omega_minFun_zero_point h y, omega_minFun_zero_point h x, hy]
    rw [Subtype.ext this]
  have hinf : (Set.range (omega (minFun 0 h)).func).Infinite := by
    have hrange : Set.range (omega (minFun 0 h)).func = ↑(omega (minFun 0 h)).domain := by
      ext y; constructor
      · rintro ⟨x, rfl⟩; rw [omega_minFun_zero_func_eq h]; exact x.prop
      · intro hy; exact ⟨⟨y, hy⟩, omega_minFun_zero_func_eq h ⟨y, hy⟩⟩
    rw [hrange]
    apply Set.infinite_of_injective_forall_mem (f := fun i : ℕ => prepend i zeroStream)
    · intro i j hij
      have := congrFun hij 0
      simpa [prepend] using this
    · intro i
      exact mem_gluingSet_prepend (minFun_zero_domain ▸ rfl)
  exact locally_constant_infinite_image hlc hinf

/-- **Level `1` is finitely generated by `𝒢_1 = {k_1, ω k_1}`.**  Case split on whether
`F.func` has finite or infinite image (`isLocallyConstant_of_cbRank_le_one` gives local
constancy from `CBRank F.func = 1`):

* Finite image (size `N`): reuses the *general* (not `genLeOne`-specific) construction lemmas
  `glCopies_reduces_of_enum`/`reduces_glCopies_of_enum` to get `F ≡ Gl genLeOne ![N, 0]`; since
  the multiplicity at slot `1` is `0`, this is `≡`-irrelevantly `= glList (List.replicate N k_1)`
  (`Gl_eq_glList_copiesList` + `copiesList_indicator_mult`) regardless of what sits in slot `1`
  of `genLeOne` — so `ℓ_1` never actually enters. Transfers to `𝒢_1` via the `k_1`-index given
  by `Finset.exists_toFinFun_eq`.
* Infinite image: `F ≡ id_ℕ ≡ ω k_1` (`locally_constant_infinite_image` +
  `omega_minFun_zero_equiv_id`), transferred to `𝒢_1` via the `ω k_1`-index. -/
theorem Generators_one_finitely_generates :
    ∀ F : ScatFun, CBRank F.func = 1 → F ∈ FinGl (Generators 1).toFinFun := by
  intro F hF
  have hlc : IsLocallyConstant F.func := isLocallyConstant_of_cbRank_le_one F (le_of_eq hF)
  have hzo : (0 : Ordinal.{0}) < omega1 := zero_lt_omega1
  rw [Generators_one_eq hzo]
  rcases Set.finite_or_infinite (Set.range F.func) with hfin | hinf
  · -- Finite image: reuse the `genLeOne`-construction lemmas, then peel off `ℓ_1`.
    classical
    have : Finite ↥(Set.range F.func) := hfin
    set N := Nat.card ↥(Set.range F.func) with hN
    let e : ↥(Set.range F.func) ≃ Fin N := Finite.equivFin _
    let idxF : ↥F.domain → Fin N := fun x => e ⟨F.func x, Set.mem_range_self x⟩
    let valF : Fin N → Baire := fun k => (e.symm k).val
    have hsec : ∀ x, valF (idxF x) = F.func x := by
      intro x; simp only [valF, idxF, Equiv.symm_apply_apply]
    have hvalinj : Function.Injective valF :=
      fun a b hab => e.symm.injective (Subtype.ext hab)
    have hidx : Continuous idxF := continuous_of_discreteTopology.comp (F.hCont.subtype_mk _)
    have hsurj : Function.Surjective idxF := by
      intro k
      obtain ⟨v, hv⟩ := (e.symm k).2
      refine ⟨v, ?_⟩
      show e ⟨F.func v, Set.mem_range_self v⟩ = k
      rw [show (⟨F.func v, Set.mem_range_self v⟩ : ↥(Set.range F.func)) = e.symm k from
        Subtype.ext hv, e.apply_symm_apply]
    let rep : Fin N → ↥F.domain := fun k => (hsurj k).choose
    have hrep : ∀ k, F.func (rep k) = valF k := by
      intro k
      have h1 : idxF (rep k) = k := (hsurj k).choose_spec
      rw [← hsec (rep k), h1]
    have hmult : (![N, 0] : Fin 2 → ℕ) = fun j => if j = 0 then N else 0 := by
      funext j; fin_cases j <;> rfl
    have hGleq : Gl genLeOne ![N, 0] = glList (List.replicate N (minFun 0 zero_lt_omega1)) := by
      rw [Gl_eq_glList_copiesList, hmult, copiesList_indicator_mult]; rfl
    obtain ⟨i, hi⟩ := ({minFun 0 hzo, omega (minFun 0 hzo)} : Finset ScatFun).exists_toFinFun_eq
      (Finset.mem_insert_self _ _)
    refine ⟨fun j => if j = i then N else 0, ?_, ?_⟩
    · rw [Gl_eq_glList_copiesList, copiesList_indicator_mult, hi]
      rw [← hGleq]
      exact glCopies_reduces_of_enum F N valF hvalinj rep hrep
    · rw [Gl_eq_glList_copiesList, copiesList_indicator_mult, hi]
      rw [← hGleq]
      exact reduces_glCopies_of_enum F N idxF hidx valF hsec
  · -- Infinite image: `F ≡ id_ℕ ≡ ω k_1`.
    have hid : ContinuouslyEquiv F.func (@id ℕ) := locally_constant_infinite_image hlc hinf
    have hω : ContinuouslyEquiv F.func (omega (minFun 0 hzo)).func :=
      hid.trans (omega_minFun_zero_equiv_id hzo).symm
    obtain ⟨i, hi⟩ := ({minFun 0 hzo, omega (minFun 0 hzo)} : Finset ScatFun).exists_toFinFun_eq
      (Finset.mem_insert_of_mem (Finset.mem_singleton_self _))
    refine ⟨fun j => if j = i then 1 else 0, ?_, ?_⟩
    · rw [Gl_eq_glList_copiesList, copiesList_indicator_mult, hi, List.replicate_one]
      exact (glList_single_equiv (omega (minFun 0 hzo))).2.trans hω.2
    · rw [Gl_eq_glList_copiesList, copiesList_indicator_mult, hi, List.replicate_one]
      exact hω.1.trans (glList_single_equiv (omega (minFun 0 hzo))).1

/- **Finite generation of `CB`-rank levels.**  For every `α < ω₁`, every `F : ScatFun` of
`CB`-rank `α` lies in `FinGl (Generators α).toFinFun`.

This is the key structural result of the memoir (the `𝒞_α` are finitely generated). It cannot be
stated in *this* file: it is assembled (by strong induction on `α`) from the level-by-level
instances above together with `Two.lean`/`LambdaPlusOne.lean`, both of which import this file —
stating it here would make the import graph circular. See `ScatFun.levels_finitely_generated` in
`LevelsFinitelyGenerated/Induction.lean` (its two remaining open leaves are the §6.4
solvable-functions inputs in `Solvable.lean`, feeding the general successor-of-successor step). -/

end ScatFun

end
