import WqoContinuousFunctions.ScatFun.ReflectLevel
import WqoContinuousFunctions.ScatFun.Generators.Defs
import WqoContinuousFunctions.ScatFun.LevelsFinitelyGenerated.GlList
import WqoContinuousFunctions.CenteredFunctions.FinitenessHelpers

open scoped Topology
open Set Function TopologicalSpace Classical

set_option autoImplicit false

noncomputable section

/-!
# From finite generation to 2-BQO, level by level

Bridges the level-by-level finite-generation results (`Generators_zero_finitely_generates`,
`Generators_one_finitely_generates`, `Generators_lambda_finitely_generates`,
`Generators_lambdaPlusOne_finitely_generates`, `Generators_two_finitely_generates`) to the
2-BQO statements needed to *state* the extra hypothesis those successor-case theorems require
(`hbqo : TwoBQO (ScatFun.LevelLT.reduces (lam + 1))`), without going through the (still
unproven) global `ScatFun.levels_finitely_generated`.

* `Level.isTwoBQO_of_FG` — a single level `β`'s finite generation gives 2-BQO of `Level β`
  (the same argument as `ScatFun.Level.isTwoBQO` in `MainResults/ScatFunBQO.lean`, parametrised
  by an explicit finite-generation hypothesis instead of the global theorem).
* `LevelLT.isTwoBQO_of_FG_below` — finite generation at every `β < α` gives 2-BQO of
  `LevelLT α`, via `bad_restricts_to_level` (any bad pair-sequence on `LevelLT α` restricts to a
  single level `β < α`, contradicting 2-BQO there).
* `FinGl_mono_of_subset` — `FinGl` is monotone under `Finset`-inclusion of the generating
  family: reuses `finGl_glList_of_forall_mem` (every block of a finite gluing over `S` is
  literally a member of `S`, hence of any `S' ⊇ S`) and `finGl_closed_equiv`.
* `Generators_mono_of_le` — for `lam` limit-or-zero, `Generators (lam+k) ⊆ Generators (lam+n)`
  whenever `k ≤ n` (monotonicity of the block recursion `GenBlock`, `GenBlock_subset_succ`).
* `LevelInter_finitelyGenerated` — for `lam` limit-or-zero and `n : ℕ`, if every level `lam+k`
  (`k ≤ n`) is finitely generated by its own `Generators (lam+k)`, then the whole interval
  `LevelInter lam (lam+n)` is finitely generated by the top-level family `Generators (lam+n)`
  alone (via `Generators_mono_of_le` + `FinGl_mono_of_subset`).  This is exactly the `hgen`
  hypothesis consumed by `finitenessOfCenteredFunctions` (`CenteredFunctions/Finiteness.lean`).
-/

namespace ScatFun

/-- **A single level's 2-BQO from its finite generation.**  By `FinGl.isTwoBQO`, `FinGl B` is
2-BQO for any finite `B`; pull back along the inclusion `Level β ↪ FinGl B` witnessed by `hB`. -/
theorem Level.isTwoBQO_of_FG {β : Ordinal.{0}}
    (hB : ∀ F : ScatFun, CBRank F.func = β → F ∈ FinGl (Generators β).toFinFun) :
    TwoBQO (ScatFun.Level.reduces β) :=
  (ScatFun.FinGl.isTwoBQO (ScatFun.Generators β).toFinFun).comap
    (fun F : ScatFun.Level β => ⟨F.val, hB F.val F.prop⟩)

/-- **`LevelLT α` is 2-BQO from finite generation at every level below `α`.**

Given a bad pair-sequence `f` on `LevelLT α`, forget to a bad pair-sequence on `ScatFun` and
apply `bad_restricts_to_level`: it restricts to a single level `β < ω₁`.  Since every value of
`f` has `CBRank < α`, so does the restricted subsequence, hence `β < α`; `hFG β` then gives
2-BQO of `Level β` (`Level.isTwoBQO_of_FG`), contradicting the restricted subsequence's
badness. -/
theorem LevelLT.isTwoBQO_of_FG_below {α : Ordinal.{0}}
    (hFG : ∀ β < α, ∀ F : ScatFun, CBRank F.func = β → F ∈ FinGl (Generators β).toFinFun) :
    TwoBQO (ScatFun.LevelLT.reduces α) := by
  rw [TwoBQO.iff_noBad]
  rintro ⟨f, hbad⟩
  have hbad' : PairSeq.IsBad ScatFun.Reduces (fun m n h => (f m n h).val) :=
    fun m n l hmn hnl => hbad m n l hmn hnl
  obtain ⟨β, hβlt, e, he, hbad_level, hrank⟩ :=
    ScatFun.bad_restricts_to_level (fun m n h => (f m n h).val) hbad'
  have h01 : CBRank (f (e 0) (e 1) (he (by norm_num))).val.func = β := hrank 0 1 (by norm_num)
  have hβα : β < α := h01 ▸ (f (e 0) (e 1) (he (by norm_num))).prop
  let f_β : PairSeq (ScatFun.Level β) :=
    fun m n h => ⟨PairSeq.restrict (fun m n h => (f m n h).val) e he m n h, hrank m n h⟩
  exact (TwoBQO.iff_noBad _).mp (ScatFun.Level.isTwoBQO_of_FG (hFG β hβα))
    ⟨f_β, fun m n l hmn hnl hrel => hbad_level m n l hmn hnl hrel⟩

/-! ## `FinGl` monotonicity under `Finset`-inclusion of the generating family -/

/-- Every block of a finite gluing over `S.toFinFun` is literally a member of `S`. -/
lemma copiesList_toFinFun_subset {S : Finset ScatFun} (t : Fin S.card → ℕ) :
    ∀ w ∈ ScatFun.copiesList S.toFinFun t, w ∈ S := by
  intro w hw
  simp only [ScatFun.copiesList, List.mem_flatMap, List.mem_finRange, List.mem_replicate,
    true_and] at hw
  obtain ⟨i, -, rfl⟩ := hw
  exact Finset.mem_toList.mp (List.get_mem S.toList _)

/-- **`FinGl` is monotone under `Finset`-inclusion of the generating family.**  A finite gluing
over `S.toFinFun` is a `glList` of blocks all lying in `S` (`copiesList_toFinFun_subset`), hence
(since `S ⊆ S'`) all lying in `S'`; `finGl_glList_of_forall_mem` then places it in
`FinGl S'.toFinFun`, and `finGl_closed_equiv` transfers this along the defining equivalence to
every member of `FinGl S.toFinFun`. -/
theorem FinGl_mono_of_subset {S S' : Finset ScatFun} (h : S ⊆ S') :
    ScatFun.FinGl S.toFinFun ⊆ ScatFun.FinGl S'.toFinFun := by
  intro f hf
  obtain ⟨t, ht1, ht2⟩ := hf
  have hL : ∀ w ∈ ScatFun.copiesList S.toFinFun t, w ∈ S' :=
    fun w hw => h (copiesList_toFinFun_subset t w hw)
  have hmem := finGl_glList_of_forall_mem hL
  rw [← ScatFun.Gl_eq_glList_copiesList] at hmem
  exact finGl_closed_equiv _ hmem ⟨ht1, ht2⟩

/-! ## Monotonicity of `Generators` across a fixed limit-or-zero block -/

/-- `GenBlock G0 C1` is monotone in its `ℕ`-index (immediate from `GenBlock_subset_succ`). -/
theorem GenBlock_mono (G0 C1 : Finset ScatFun) : Monotone (GenBlock G0 C1) :=
  monotone_nat_of_le_succ (GenBlock_subset_succ G0 C1)

/-- **`Generators` is monotone across a fixed limit-or-zero block.**  For `lam` limit-or-zero,
`Generators (lam+k) ⊆ Generators (lam+n)` whenever `k ≤ n`: both sides unfold to `GenBlock
(genBase lam) (centBase1 lam)` at index `k`/`n` (`Ordinal.limitPart_add_natCast`/
`natPart_add_natCast`), so this is `GenBlock_mono`. -/
theorem Generators_mono_of_le {lam : Ordinal.{0}} (hlim : Order.IsSuccLimit lam ∨ lam = 0)
    {k n : ℕ} (hkn : k ≤ n) :
    Generators (lam + k) ⊆ Generators (lam + n) := by
  have hGk : Generators (lam + k) = GenBlock (genBase lam) (centBase1 lam) k := by
    unfold Generators
    rw [Ordinal.limitPart_add_natCast lam k hlim, Ordinal.natPart_add_natCast lam k hlim]
  have hGn : Generators (lam + n) = GenBlock (genBase lam) (centBase1 lam) n := by
    unfold Generators
    rw [Ordinal.limitPart_add_natCast lam n hlim, Ordinal.natPart_add_natCast lam n hlim]
  rw [hGk, hGn]
  exact GenBlock_mono (genBase lam) (centBase1 lam) hkn

/-! ## Finite generation of a level interval `[lam, lam+n]` -/

/-- **A finitely-generated block generates its whole interval.**  For `lam` limit-or-zero and
`n : ℕ`, if every level `lam+k` (`k ≤ n`) is finitely generated by its own `Generators (lam+k)`,
then the whole interval `LevelInter lam (lam+n)` is finitely generated by the top-level family
`Generators (lam+n)` alone.

Every `F` in the interval has `CBRank F.func = lam + k` for a (unique) `k ≤ n` — extracting `k`
is ordinal arithmetic (`exists_add_of_le` gives the offset `δ`, `add_le_add_iff_left` bounds it
by `n`, `Ordinal.lt_omega0` reads it off as a natural number) — and `hFG` places `F` in
`FinGl (Generators (lam+k)).toFinFun`, which embeds into `FinGl (Generators (lam+n)).toFinFun`
via `Generators_mono_of_le` and `FinGl_mono_of_subset`.  This is exactly the `hgen` hypothesis
consumed by `finitenessOfCenteredFunctions` (`CenteredFunctions/Finiteness.lean`). -/
theorem LevelInter_finitelyGenerated {lam : Ordinal.{0}} (hlim : Order.IsSuccLimit lam ∨ lam = 0)
    (n : ℕ)
    (hFG : ∀ k ≤ n, ∀ F : ScatFun, CBRank F.func = lam + k →
      F ∈ FinGl (Generators (lam + k)).toFinFun) :
    ScatFun.LevelInter lam (lam + n) ⊆ ScatFun.FinGl (Generators (lam + n)).toFinFun := by
  intro F hF
  obtain ⟨hge, hle⟩ := hF
  obtain ⟨δ, hδ⟩ := exists_add_of_le hge
  have hδn : δ ≤ (n : Ordinal.{0}) := by
    have h1 : lam + δ ≤ lam + (n : Ordinal.{0}) := hδ ▸ hle
    exact (add_le_add_iff_left lam).mp h1
  have hδlt : δ < Ordinal.omega0 :=
    lt_of_le_of_lt hδn (by exact_mod_cast Ordinal.nat_lt_omega0 n)
  obtain ⟨k, hk⟩ := Ordinal.lt_omega0.mp hδlt
  have hkn : k ≤ n := by exact_mod_cast (hk ▸ hδn : (k : Ordinal.{0}) ≤ (n : Ordinal.{0}))
  have hFk : F ∈ FinGl (Generators (lam + k)).toFinFun := hFG k hkn F (by rw [hδ, hk])
  exact FinGl_mono_of_subset (Generators_mono_of_le hlim hkn) hFk

end ScatFun

end
