import WqoContinuousFunctions.ScatFun.LevelsFinitelyGenerated.LevelsFinitelyGenerated
import WqoContinuousFunctions.ScatFun.LevelsFinitelyGenerated.LambdaPlusOne
import WqoContinuousFunctions.ScatFun.LevelsFinitelyGenerated.GlList
import WqoContinuousFunctions.ScatFun.Wedge.Monotone
import WqoContinuousFunctions.CenteredFunctions.SimpleSuccessorOfLimit
import WqoContinuousFunctions.ScatFun.PreciseStructure.DiagonalForLambdaPlusOne
import ZeroDimensionalSpaces.IsolatingSequences
import WqoContinuousFunctions.ScatFun.PreciseStructure.DiagonalClassReduces

open scoped Topology
open Set Function TopologicalSpace Classical

set_option autoImplicit false

noncomputable section

/-!
# Finite generation at `CB`-rank `2` (memoir `FGatsuccessoroflimit`, case `λ = 1`)

`FGatsuccessoroflimit` (`5_precise_struct_memo.tex:378`) states `FG(λ+1)` for `λ` limit *or*
`1`, assuming `FG(<λ)` (i.e. continuous reducibility is `BQO` on `𝒞_{<λ}`).  Specialised to
`λ = 1` this gives `FG(2)`; together with `Generators_lambdaPlusOne_finitely_generates`
(`ScatFun/LevelsFinitelyGenerated/LambdaPlusOne.lean`, the `λ` non-zero-limit case) it covers
the full successor-of-(limit-or-`1`) statement.
-/

namespace ScatFun

/-- **2-BQO on `CB`-rank `< 1`.**  Every `F` of rank `< 1` (i.e. rank `0`) has empty domain
(`CBRank_pos_of_scattered_nonempty`), and `reduces_of_isEmpty_domain` makes any two such
functions mutually reducible — so `LevelLT.reduces 1` is (trivially) a total relation, hence
2-BQO for free. Unlike the genuine non-zero-limit case, no induction hypothesis is needed
here: `𝒞_0` is degenerate. -/
lemma twoBQO_levelLT_one : TwoBQO (ScatFun.LevelLT.reduces (1 : Ordinal.{0})) := by
  intro f
  have hempty : ∀ m n (hmn : m < n), IsEmpty ↑(f m n hmn).val.domain := by
    intro m n hmn
    by_contra h
    rw [not_isEmpty_iff] at h
    exact absurd (Ordinal.lt_one_iff_zero.mp (f m n hmn).2)
      (ne_of_gt (CBRank_pos_of_scattered_nonempty (f m n hmn).val.func (f m n hmn).val.hScat h))
  exact ⟨0, 1, 2, by norm_num, by norm_num, reduces_of_isEmpty_domain (hempty 0 1 (by norm_num))⟩

/-- **2-BQO on `CB`-rank `< 2` (i.e. `≤ 1`), unconditionally.**  Reuses the already-proved
`lamOne_twoBQO_levelLT_two` (`CenteredFunctions/SimpleSuccessor/LamOne.lean:349`), whose own
`_hbqo : TwoBQO (LevelLT.reduces 1)` argument is in fact unused (its proof only needs
`cLeOne_finitely_generated` + `FinGl.isTwoBQO`) — matching the observation that `𝒞_{≤1}` is
already finitely generated by `Generators 0`/`Generators 1`, so 2-BQO there is not an
assumption but a *consequence* already on hand. -/
lemma twoBQO_levelLT_two : TwoBQO (ScatFun.LevelLT.reduces (2 : Ordinal.{0})) := by
  have h := lamOne_twoBQO_levelLT_two twoBQO_levelLT_one
  have h2 : (1 + 1 : Ordinal.{0}) = 2 := by norm_num
  rwa [h2] at h

/-
**Finite-degree functions of `CB`-rank `2` are finitely generated** (memoir Corollary
`finitedegreedamuddafuckaz`, `4_centered_memo.tex:372`, `λ = 1` instance).

"Finite degree" is stated directly as: the image of the last non-empty `CB`-level
(`CBLevel F.func 1`, since `CBRank F.func = 2 = 1 + 1`) is finite — matching the definition of
`N_f` in `2_prelim_memo.tex:413` (the `CB`-degree primitive itself, `N_f`, is not yet in the
Lean development; see the note at `CenteredFunctions/SimpleSuccessor/Prop411.lean:37`).

No `hbqo` hypothesis is needed: unlike the genuine non-zero-limit case (`LambdaPlusOne.lean`),
2-BQO on `𝒞_{≤1}` is already established (`twoBQO_levelLT_two` above), not an assumption of
the induction.

## Proof strategy (now formalised; see `Generators_two_finitely_generates_of_finite_degree`
and its supporting lemmas `Fb_isolated_glList_two`, `pglFinset_k1_mem_Generators_two`, etc.,
near the end of this file)

* **Decomposition into simple pieces** (memoir Corollary `FiniteDegreeAreFinGl`,
  `2_prelim_memo.tex:684`): a finite clopen partition `(Bᵢ)_{i≤n}` of the codomain, each piece
  containing exactly one point of `F.func '' CBLevel F.func 1`, gives corestrictions
  `F ↾ Bᵢ` that are simple of rank `2` (their own last CB-level is a singleton). Assembling
  these via `reduces_F_gl_of_codomain`/`reduces_gl_F_of_codomain`
  (`CenteredFunctions/SimpleSuccessor/Prop411.lean:298,433`, currently stated for `ℕ`-indexed
  families — padding the finite partition with `∅` pieces beyond index `n` reduces to that
  case) yields `F ≡ Gl (fun i => Fᵢ) ![1,…,1]` for these simple `Fᵢ`.
* **Classifying each simple piece** (`simpleFunctionsLambdaPlusOne`, specialised to `lam = 1`
  with `hbqo := twoBQO_levelLT_one`, `CenteredFunctions/SimpleSuccessorOfLimit.lean:232`):
  each `Fᵢ ≡ minFun 1 h`, `minFun 1 h ⊕ maxFun 1 h`, or `succMaxFun 1 h` — the three
  candidate generators of `AlreadyKnownGenerators` at `λ = 1`.
* **Placing the three generators in `Generators 2`**: `Generators_two_eq` below unfolds
  `Generators 2 = GenBlock (genBase 0) (centBase1 0) 2` one `genStep` deep; still needed is
  showing `{minFun 1 h, minFun 1 h ⊕ maxFun 1 h, succMaxFun 1 h} ⊆ Generators 2` from that
  unfolding, then transferring the `FinGl`-membership of each `Fᵢ` along
  `Finset.exists_toFinFun_eq` as in `Generators_one_finitely_generates`.
-/
-- `Generators_two_finitely_generates_of_finite_degree` is stated and proved near the end of
-- this file (after the helper infrastructure it depends on has been developed).

/-! ## The infinite-`CB`-degree case

This is the bulk of the proof of `FGatsuccessoroflimit` (`5_precise_struct_memo.tex:385-422`)
specialised to `λ = 1`: once the finite-degree case has been peeled off
(`Generators_two_finitely_generates_of_finite_degree` above, memoir corollary
`finitedegreedamuddafuckaz`), every remaining `F` of `CB`-rank `2` decomposes as a countable
disjoint union `F = ⊔ₙ Fₙ` of *simple* blocks of rank `2` with *pairwise distinct* distinguished
points `yₙ` (memoir's Decomposition Lemma `JSLdecompositionlemma`, `2_prelim_memo.tex:478`, Lean
`decomposition_lemma_baire`/`IsLocallyInClass`, `ContinuousReducibility/Scattered/Decomposition.lean`,
refined to a countable clopen partition via `locally_implies_disjointUnion_nat`
(`CenteredFunctions/SimpleSuccessor/Shared.lean:908`) already used for the analogous Case-B
decomposition inside `simple_dichotomy_lam_one`/`lamOne_caseB_decomposition`; merging
same-distinguished-point blocks together needs the restriction-closed refinement of "simple of
rank `2`" analogous to the prefix-cylinder strengthening `scatFun_centered_cylinder_witness` used
for the centered decomposition (Theorem 4.7) — not yet in the Lean development, and the first
genuinely new piece of infrastructure this case needs).

By `simpleFunctionsLambdaPlusOne` (Theorem 4.12 at `lam = 1`, fed `twoBQO_levelLT_one` above —
no external `hbqo` needed, unlike the non-zero-limit case in `LambdaPlusOne.lean`), each block
`Fₙ` is equivalent to one of `minFun 1 h`, `minFun 1 h ⊕ maxFun 1 h`, or `succMaxFun 1 h`. Set
`N₁ := {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}` — the memoir's `N_1` — and split on its
cardinality, exactly mirroring `LambdaPlusOne.lean`'s `case_N1_infinite` /
`case_N1_empty` / `case_N1_finite_nonempty` (specialised to `lam = 1`; the ordinal-generic
argument of each case does not use limitness of `lam`, so the same proof strategy applies
verbatim here). -/

/-- `ω` is a congruence for continuous equivalence: `a ≡ b → ω a ≡ ω b`. -/
lemma omega_equiv_congr {a b : ScatFun} (hab : Equiv a b) : Equiv (omega a) (omega b) :=
  ⟨gl_reduces_of_pointwise _ _ (fun _ => hab.1), gl_reduces_of_pointwise _ _ (fun _ => hab.2)⟩

/-- Constant-family pointed gluing is a congruence: `a ≡ b → pgl (const a) ≡ pgl (const b)`. -/
lemma pgl_const_equiv_congr {a b : ScatFun} (hab : Equiv a b) :
    Equiv (pgl (fun _ => a)) (pgl (fun _ => b)) :=
  ⟨pgl_reduces_pgl _ _ (fun _ j₀ => ⟨j₀, le_rfl, hab.1⟩),
   pgl_reduces_pgl _ _ (fun _ j₀ => ⟨j₀, le_rfl, hab.2⟩)⟩

/-- `(2 : Ordinal).natPart = 2`. -/
lemma natPart_two : (2 : Ordinal.{0}).natPart = 2 := by
  have h0 : (2 : Ordinal.{0}) = (0 : Ordinal.{0}) + (2 : ℕ) := by norm_num
  rw [h0, Ordinal.natPart_add_natCast 0 2 (Or.inr rfl)]

/-- `(2 : Ordinal).limitPart = 0`. -/
lemma limitPart_two : (2 : Ordinal.{0}).limitPart = 0 := by
  have h0 : (2 : Ordinal.{0}) = (0 : Ordinal.{0}) + (2 : ℕ) := by norm_num
  rw [h0, Ordinal.limitPart_add_natCast 0 2 (Or.inr rfl)]

/-- Unfolding of `Generators 2` into its level-`1` block and the single `genStep`, mirroring
`Generators_add_one_eq`/`Generators_one_eq` one recursion step further down (`Generators 2 =
GenBlock (genBase 0) (centBase1 0) 2`, i.e. `n = 1 + 1` rather than `n = 0 + 1`). -/
lemma Generators_two_eq :
    Generators 2 = GenBlock (genBase 0) (centBase1 0) 1 ∪
      genStep (CentBlock (centBase1 0) 1) (GenBlock (genBase 0) (centBase1 0) 1) := by
  rw [Generators, natPart_two, limitPart_two, show (2 : ℕ) = 1 + 1 from rfl]
  simp only [GenBlock]

/-- `ω (pgl ℓ₁) ≡ ω (succMaxFun 1)` where `ℓ₁ = maxFun 1`: the equivalence chain
`pglFinset {ω k₁} ≡ pgl (const ω k₁) ≡ pgl (const ℓ₁) = succMaxFun 1`, then apply `ω`. -/
lemma omega_succMaxFun_one_equiv_gen (h : (1 : Ordinal.{0}) < omega1) :
    Equiv (omega (succMaxFun 1 h))
      (omega (pglFinset {omega (minFun 0 zero_lt_omega1)})) := by
  set k1 := minFun 0 zero_lt_omega1 with hk1
  have hA : Equiv (omega k1) (maxFun 1 h) := by
    have h1 : ContinuouslyEquiv (omega k1).func (@id ℕ) := omega_minFun_zero_equiv_id zero_lt_omega1
    have h2 : ContinuouslyEquiv (maxFun 1 h).func (@id ℕ) := by
      rw [maxFun_func]; exact maxFun_one_equiv_id
    exact ⟨(h1.trans h2.symm).1, (h1.trans h2.symm).2⟩
  have htl : ({omega k1} : Finset ScatFun).toList = [omega k1] := by simp
  have hpf : pglFinset {omega k1} = pgl (fun _ => glList [omega k1]) := by
    unfold pglFinset; rw [htl]
  have hD : Equiv (pglFinset {omega k1}) (pgl (fun _ => omega k1)) := by
    rw [hpf]; exact pgl_const_equiv_congr (glList_single_equiv (omega k1)).symm
  have hB : Equiv (pgl (fun _ => omega k1)) (succMaxFun 1 h) := by
    have hbb := pgl_const_equiv_congr hA
    rwa [← succMaxFun_eq] at hbb
  have hE : Equiv (succMaxFun 1 h) (pglFinset {omega k1}) := (hD.trans hB).symm
  exact omega_equiv_congr hE

/-- `ω (pgl ℓ₁)` is one of the generators in `Generators 2` (up to defeq): it is the `ω`-image of
`pglFinset {ω k₁} ∈ CentBlock {k₁} 1`. -/
lemma omega_pglFinset_mem_Generators_two :
    omega (pglFinset {omega (minFun 0 zero_lt_omega1)}) ∈ Generators 2 := by
  set k1 := minFun 0 zero_lt_omega1 with hk1
  have hcent : pglFinset {omega k1} ∈ CentBlock {k1} 1 := by
    show pglFinset {omega k1} ∈ centStep {k1}
    rw [centStep]
    apply Finset.mem_union_right
    rw [Finset.mem_image]
    refine' ⟨{omega k1}, _, rfl⟩
    unfold nonemptySubsets
    rw [Finset.mem_erase]
    refine ⟨by simp, ?_⟩
    rw [Finset.mem_powerset]
    intro x hx
    simp only [Finset.mem_singleton] at hx
    subst hx
    simp [omegaImage]
  have hom : omega (pglFinset {omega k1}) ∈ omegaImage (CentBlock {k1} 1) :=
    Finset.mem_image_of_mem omega hcent
  rw [Generators_two_eq]
  apply Finset.mem_union_right
  rw [genStep]
  apply Finset.mem_union_left
  apply Finset.mem_union_right
  have hcb : centBase1 0 = {k1} := by
    unfold centBase1; rw [if_pos rfl, dif_pos zero_lt_omega1]
  rw [hcb]
  exact hom

lemma omega_succMaxFun_one_mem_finGl_two (h : (1 : Ordinal.{0}) < omega1) :
    omega (succMaxFun 1 h) ∈ FinGl (Generators 2).toFinFun :=
  finGl_single_of_equiv omega_pglFinset_mem_Generators_two (omega_succMaxFun_one_equiv_gen h)

/-- `ω ℓ_α` acts as the identity on its domain (`ℓ_α = MaxFun α = Subtype.val`). -/
lemma omega_maxFun_func_val (α : Ordinal.{0}) (hα : α < omega1)
    (x : ↑(omega (maxFun α hα)).domain) : (omega (maxFun α hα)).func x = x.val := by
  obtain ⟨yv, hy⟩ := x
  have hy' : yv ∈ GluingSet (fun _ => (maxFun α hα).domain) := hy
  obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hy'
  obtain ⟨z, hz, rfl⟩ := hi
  have hval : (maxFun α hα).func ⟨z, hz⟩ = z := by rw [maxFun_func]; rfl
  calc (omega (maxFun α hα)).func ⟨prepend i z, hy⟩
      = prepend i ((maxFun α hα).func ⟨z, hz⟩) := omega_func_prepend (maxFun α hα) i ⟨z, hz⟩
    _ = prepend i z := by rw [hval]

/-- **Self-similarity of `ℓ_α`: `ω ℓ_α ≤ ℓ_α`.**  Both sides have the same domain
`GluingSet (fun _ => MaxDom α)` and act as `Subtype.val`, so this is
`gluingSet_copies_reduces_to_MaxFun`. -/
lemma omega_maxFun_reduces_self (α : Ordinal.{0}) (hα : α < omega1) :
    Reduces (omega (maxFun α hα)) (maxFun α hα) := by
  have hfun : (omega (maxFun α hα)).func = fun x => x.val := funext (omega_maxFun_func_val α hα)
  show ContinuouslyReduces (omega (maxFun α hα)).func (maxFun α hα).func
  rw [hfun, maxFun_func]
  exact gluingSet_copies_reduces_to_MaxFun α hα

/-- **Upper bound for a rank-`2` disjoint union: `F ≤ ω (succMaxFun 1)`.**  Each block reduces to
`ℓ₂ = maxFun 2` (rank `2`), so `F ≤ gl blocks ≤ ω ℓ₂ ≡ ℓ₂ ≤ ω (succMaxFun 1)` (bridge lemma). -/
lemma reduces_omega_succMaxFun_one_of_rank_two (h : (1 : Ordinal.{0}) < omega1)
    (h2 : (2 : Ordinal.{0}) < omega1) (F : ScatFun) (A : ℕ → Set ↑F.domain)
    (hdu : F.IsDisjointUnion A) (hrank : ∀ n, CBRank (F.restrict (A n)).func = 2) :
    Reduces F (omega (succMaxFun 1 h)) := by
  have step1 : Reduces F (gl (fun n => F.restrict (A n))) :=
    scatFun_reduces_gl_of_domain_partition F A hdu
  have hblock : ∀ n, Reduces (F.restrict (A n)) (maxFun 2 h2) := by
    intro n
    have hcb : ∀ β : Ordinal.{0}, (2 : Ordinal.{0}) ≤ β → CBLevel (F.restrict (A n)).func β = ∅ := by
      intro β hβ
      exact CBLevel_empty_of_le_rank _ (F.restrict (A n)).hScat β (by rw [hrank n]; exact hβ)
    exact (maxFun_is_maximum 2 h2).1 (F.restrict (A n)).func (F.restrict (A n)).hCont
      (F.restrict (A n)).hScat hcb
  have step2 : Reduces (gl (fun n => F.restrict (A n))) (omega (maxFun 2 h2)) :=
    gl_reduces_of_pointwise _ _ hblock
  have step3 : Reduces (omega (maxFun 2 h2)) (maxFun 2 h2) := omega_maxFun_reduces_self 2 h2
  have step4 : Reduces (maxFun 2 h2) (omega (succMaxFun 1 h)) := by
    have h11 : (1 : Ordinal.{0}) + 1 < omega1 := by
      rw [show (1 : Ordinal.{0}) + 1 = 2 by norm_num]; exact h2
    have hbase := maxFun_reduces_omega_succMaxFun 1 h h11
    convert hbase using 2
    norm_num
  exact step1.trans (step2.trans (step3.trans step4))

/-- **Center-transport membership.**  If the block `F.restrict (A n)` is equivalent to the centered
function `succMaxFun 1 h`, then the block's distinguished point `y n` belongs to
`IntertwineSet F (succMaxFun 1 h)`.  This is the `hmapsto` step of
`intertwine_reductions_omega_centered_piece`, packaged for a single block. -/
lemma yn_mem_intertwineSet (h : (1 : Ordinal.{0}) < omega1) (F : ScatFun)
    (A : ℕ → Set ↑F.domain) (hdu : F.IsDisjointUnion A) (y : ℕ → Baire)
    (hdist : ∀ n, ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n)
    (n : ℕ) (hrankn : CBRank (F.restrict (A n)).func = 2)
    (hn : Equiv (F.restrict (A n)) (succMaxFun 1 h)) :
    y n ∈ IntertwineSet F (succMaxFun 1 h) := by
  set g := succMaxFun 1 h with hg
  set B := F.restrict (A n) with hB
  have hc : IsCenterFor g.func ⟨zeroStream, zeroStream_mem_pointedGluingSet _⟩ :=
    succMaxFun_base_isCenter 1 h
  set c : ↑g.domain := ⟨zeroStream, zeroStream_mem_pointedGluingSet _⟩ with hc_def
  obtain ⟨σ, hσ, τ, hτ, heq⟩ := hn.2
  have hcenterB : IsCenterFor B.func (σ c) := centerInvariance_equiv hc ⟨hn.2, hn.1⟩ hσ hτ heq
  have hne : (CBLevel B.func 1).Nonempty := by
    apply CBLevel_nonempty_below_rank B.func B.hScat 1; rw [hrankn]; norm_num
  have hσc_lvl : σ c ∈ CBLevel B.func 1 := center_in_CBLevel B.func (σ c) hcenterB 1 hne
  have hval : B.func (σ c) = y n := hdist n (σ c) hσc_lvl
  set σc : ↑g.domain → ↑F.domain := fun z => ⟨(σ z).val, (σ z).2.choose⟩ with hσc_def
  have hσc_cont : Continuous σc := Continuous.subtype_mk (continuous_subtype_val.comp hσ) _
  have hFσc : ∀ z, F.func (σc z) = B.func (σ z) := fun z => rfl
  intro V hV
  rw [mem_nhds_iff] at hV
  obtain ⟨V₀, hV₀sub, hV₀open, hV₀y⟩ := hV
  set U : Set ↑F.domain := A n ∩ {w : ↑F.domain | F.func w ∈ V₀} with hU_def
  have hU_open : IsOpen U := (hdu.1 n).isOpen.inter (hV₀open.preimage F.hCont)
  have hσc_mem : σc c ∈ U := by
    refine ⟨(σ c).2.choose_spec, ?_⟩
    show F.func (σc c) ∈ V₀
    rw [hFσc c, hval]; exact hV₀y
  have hτeq : ∀ z, g.func z = τ (F.func (σc z)) := by intro z; rw [hFσc z]; exact heq z
  have hcomp : F.func ∘ σc = B.func ∘ σ := funext hFσc
  have hτc : ContinuousOn τ (Set.range (F.func ∘ σc)) := by rw [hcomp]; exact hτ
  have hCI : ContinuouslyReduces g.func (F.func ∘ (Subtype.val : ↥U → ↑F.domain)) :=
    centerInvariance_reduce hc hσc_cont hτc hτeq hU_open hσc_mem
  have hred_block : Reduces g (F.restrict U) := hCI.comp_homeomorph_right (F.restrictEquiv U)
  have hUsub : U ⊆ {z : ↑F.domain | F.func z ∈ V₀} := Set.inter_subset_right
  have hred2 : Reduces (F.restrict U) (F.coRestrict V₀) := restrict_reduces_of_subset F hUsub
  have hred3 : Reduces (F.coRestrict V₀) (F.coRestrict V) := coRestrict_reduces_of_subset F hV₀sub
  exact hred_block.trans (hred2.trans hred3)

/-- **Lower bound (crux): `ω (succMaxFun 1) ≤ F`** when infinitely many blocks are `≡ succMaxFun 1`
with pairwise-distinct distinguished points.  Each such distinguished point `y n` lies in
`IntertwineSet F (succMaxFun 1)` (`yn_mem_intertwineSet`), so that set is infinite and
`intertwine_reductions` applies (with the single-block family `fun _ : Fin 1 => succMaxFun 1`). -/
lemma omega_succMaxFun_one_reduces_of_infinite (h : (1 : Ordinal.{0}) < omega1)
    (F : ScatFun) (A : ℕ → Set ↑F.domain) (hdu : F.IsDisjointUnion A)
    (y : ℕ → Baire) (hy_inj : Function.Injective y)
    (hrank : ∀ n, CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ n, ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n)
    (hN1_inf : {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}.Infinite) :
    Reduces (omega (succMaxFun 1 h)) F := by
  set g := succMaxFun 1 h with hg
  have hmem : ∀ n ∈ {n | Equiv (F.restrict (A n)) g}, y n ∈ IntertwineSet F g :=
    fun n hn => yn_mem_intertwineSet h F A hdu y hdist n (hrank n) hn
  have hsub : y '' {n | Equiv (F.restrict (A n)) g} ⊆ IntertwineSet F g := by
    rintro _ ⟨n, hn, rfl⟩; exact hmem n hn
  have himg : (y '' {n | Equiv (F.restrict (A n)) g}).Infinite := hN1_inf.image (hy_inj.injOn)
  have hInf : (IntertwineSet F g).Infinite := himg.mono hsub
  have h1 := intertwine_reductions F (fun _ : Fin 1 => g) (fun _ => hInf)
  exact (omega_equiv_congr (glFin_single_equiv g)).2.trans h1

/-- **Case `N₁` infinite** (`5_precise_struct_memo.tex:394-395`), specialised to `lam = 1`:
"By centeredness of `pgl Maximalfct{1}` we can use `Intertwinereductionsforomegacentered` again
and get `Maximalfct{2} ≤ f`. As we know that `f ≤ Maximalfct{2}` … we obtain `f ≡ Maximalfct{2}`."

## Provided solution

Identical strategy to `LambdaPlusOne.lean`'s `case_N1_infinite`, instantiated at `lam = 1`:
`succMaxFun 1 h` is centered (`succMaxFun_base_isCenter`); for `n ∈ N₁`, transporting its center
along `succMaxFun 1 h ≤ F.restrict (A n)` (`centerInvariance_equiv`) and using
`center_in_CBLevel` (`CenteredFunctions/Helpers.lean:147`) identifies the transported centre's
`F`-value with `y n`; `centerInvariance_reduce` + `reduces_block_into_coRestrict`
(`ScatFun/PreciseStructure/DiagonalForLambdaPlusOne.lean:166`) then give `y n ∈ IntertwineSet F
(succMaxFun 1 h)` for every `n ∈ N₁`. Since `N₁` is infinite with the `y n` pairwise distinct,
`intertwine_reductions` (`ScatFun/IntertwineReductions.lean:509`) gives `ω (succMaxFun 1 h) ≤ F`.
Conversely `F ≤ maxFun 2 h2` always (`Maxfunctions`/`maxFun_is_maximum`) and `maxFun 2 h2 ≤
ω (succMaxFun 1 h)` by the bridge lemma above, so `F ≡ ω (succMaxFun 1 h)`. Since
`succMaxFun 1 h ∈ centBase1 0` (unfolding `Generators 2 = GenBlock (genBase 0) (centBase1 0) 2`
as in `Generators_two_finitely_generates_of_finite_degree`'s docstring above),
`ω (succMaxFun 1 h) ∈ omegaImage (centBase1 0) ⊆ Generators 2` literally, giving `FinGl`
membership via the usual single-generator transfer (`Finset.exists_toFinFun_eq` +
`glList_single_equiv`). -/
theorem case_N1_infinite_two (h : (1 : Ordinal.{0}) < omega1) (h2 : (2 : Ordinal.{0}) < omega1)
    (F : ScatFun) (A : ℕ → Set ↑F.domain) (hdu : F.IsDisjointUnion A)
    (y : ℕ → Baire) (hy_inj : Function.Injective y)
    (hrank : ∀ n, CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ n, ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n)
    (hN1_inf : {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}.Infinite) :
    F ∈ FinGl (Generators 2).toFinFun := by
  have hlow : Reduces (omega (succMaxFun 1 h)) F :=
    omega_succMaxFun_one_reduces_of_infinite h F A hdu y hy_inj hrank hdist hN1_inf
  have hup : Reduces F (omega (succMaxFun 1 h)) :=
    reduces_omega_succMaxFun_one_of_rank_two h h2 F A hdu hrank
  exact finGl_closed_equiv _ (omega_succMaxFun_one_mem_finGl_two h) ⟨hlow, hup⟩

/-- Each rank-`2` block with a single distinguished top value is a `SimpleFun`. -/
lemma block_simpleFun (F : ScatFun) (A : ℕ → Set ↑F.domain) (y : ℕ → Baire) (n : ℕ)
    (hrank : CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n) :
    SimpleFun (F.restrict (A n)).func := by
  refine ⟨1, ?_, ?_, y n, hdist⟩
  · exact CBLevel_nonempty_below_rank _ (F.restrict (A n)).hScat 1 (by rw [hrank]; norm_num)
  · apply CBLevel_empty_of_le_rank _ (F.restrict (A n)).hScat
    rw [hrank, Order.succ_eq_add_one]; norm_num

/-- **Classification of a rank-`2` simple block** (`simpleFunctionsLambdaPlusOne` at `lam = 1`,
fed `twoBQO_levelLT_one`): every block is equivalent to one of the three level-`1` generators. -/
lemma block_classified (h : (1 : Ordinal.{0}) < omega1) (F : ScatFun) (A : ℕ → Set ↑F.domain)
    (y : ℕ → Baire) (n : ℕ) (hrank : CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n) :
    Equiv (F.restrict (A n)) (minFun 1 h) ∨
      Equiv (F.restrict (A n)) (minFun 1 h ⊕ maxFun 1 h) ∨
      Equiv (F.restrict (A n)) (succMaxFun 1 h) := by
  have hrank' : CBRank (F.restrict (A n)).func = 1 + 1 := by rw [hrank]; norm_num
  have := simpleFunctionsLambdaPlusOne 1 h (Or.inl rfl) twoBQO_levelLT_one
    (F.restrict (A n)) hrank' (block_simpleFun F A y n hrank hdist)
  simpa using this

/-
`k₂ = minFun 1 ≡ pgl(k₁) = pgl(minFun 0)` (the successor step `MinDom (β+1) = pgl(MinDom β)`).
-/
lemma minFun_one_equiv_pgl_minFun_zero (h : (1 : Ordinal.{0}) < omega1) :
    Equiv (minFun 1 h) (pgl (fun _ => minFun 0 zero_lt_omega1)) := by
  grind [pgl_const_minFun_zero_equiv_minFun_one, Equiv.symm]

/-
`ω(k₁) ≤ pgl(k₁)`: the plain gluing of countably many copies of `k₁` reduces into the
pointed gluing (`gl_reduces_pgl_direct` with the identity reindexing).
-/
lemma omega_minFun_zero_reduces_pgl :
    Reduces (omega (minFun 0 zero_lt_omega1)) (pgl (fun _ => minFun 0 zero_lt_omega1)) := by
  convert gl_reduces_pgl_direct ( fun _ => minFun 0 zero_lt_omega1 ) ( fun _ => minFun 0 zero_lt_omega1 ) id Function.injective_id ( fun _ => Or.inl rfl ) using 1;
  constructor;
  · intro h;
    convert gl_reduces_pgl_direct ( fun _ => minFun 0 zero_lt_omega1 ) ( fun _ => minFun 0 zero_lt_omega1 ) id Function.injective_id ( fun _ => Or.inl rfl ) using 1;
  · rintro ⟨ σ, τ, hσ, hτ, hτ', hσ', hτ'' ⟩;
    constructor;
    exact ⟨ hσ, τ, hτ', hτ ⟩

/-- **The stratification bound `ℓ₁ ≤ k₂`: `maxFun 1 ≤ minFun 1`.**  Chain
`maxFun 1 ≡ ω(k₁) ≤ pgl(k₁) ≡ minFun 1`, using that `ℓ₁ = ω·pgl(∅) = ω(k₁)`
(`omega_minFun_zero_equiv_id`/`maxFun_one_equiv_id`) and `k₂ = pgl(k₁)`. -/
lemma maxFun_one_reduces_minFun_one (h : (1 : Ordinal.{0}) < omega1) :
    Reduces (maxFun 1 h) (minFun 1 h) := by
  have hA : Equiv (omega (minFun 0 zero_lt_omega1)) (maxFun 1 h) := by
    have h1 : ContinuouslyEquiv (omega (minFun 0 zero_lt_omega1)).func (@id ℕ) :=
      omega_minFun_zero_equiv_id zero_lt_omega1
    have h2 : ContinuouslyEquiv (maxFun 1 h).func (@id ℕ) := by
      rw [maxFun_func]; exact maxFun_one_equiv_id
    exact ⟨(h1.trans h2.symm).1, (h1.trans h2.symm).2⟩
  exact hA.2.trans (omega_minFun_zero_reduces_pgl.trans (minFun_one_equiv_pgl_minFun_zero h).2)

/-
`minFun 1 ≤ minFun 1 ⊕ maxFun 1` (the left block of a binary gluing).
-/
lemma minFun_one_le_glBin (h : (1 : Ordinal.{0}) < omega1) :
    Reduces (minFun 1 h) (minFun 1 h ⊕ maxFun 1 h) := by
  constructor;
  refine ⟨ ?_, ?_, ?_, ?_ ⟩;
  rotate_right;
  exact fun x => ⟨ prepend 0 x.val, by
    exact Set.mem_iUnion.mpr ⟨ 0, by aesop ⟩ ⟩
  all_goals generalize_proofs at *;
  rotate_left;
  exact fun x => x ∘ ( fun n => n + 1 );
  · exact Continuous.continuousOn ( by continuity );
  · unfold minFun maxFun; aesop;
  · refine Continuous.subtype_mk ?_ ?_;
    refine continuous_pi fun i => ?_;
    induction i <;> simp +decide [ *, prepend ];
    · exact continuous_const;
    · exact continuous_apply _ |> Continuous.comp <| continuous_subtype_val

/-- `ω(minFun 1) ≡ ω(pglFinset {k₁})`, the generator equivalence for `k₂` (mirrors
`omega_succMaxFun_one_equiv_gen`, using `minFun 1 ≡ pgl(k₁) ≡ pglFinset {k₁}`). -/
lemma omega_minFun_one_equiv_gen (h : (1 : Ordinal.{0}) < omega1) :
    Equiv (omega (minFun 1 h)) (omega (pglFinset {minFun 0 zero_lt_omega1})) := by
  set k1 := minFun 0 zero_lt_omega1 with hk1
  have htl : ({k1} : Finset ScatFun).toList = [k1] := by simp
  have hpf : pglFinset {k1} = pgl (fun _ => glList [k1]) := by unfold pglFinset; rw [htl]
  have hD : Equiv (pglFinset {k1}) (pgl (fun _ => k1)) := by
    rw [hpf]; exact pgl_const_equiv_congr (glList_single_equiv k1).symm
  have hAB : Equiv (minFun 1 h) (pgl (fun _ => k1)) := minFun_one_equiv_pgl_minFun_zero h
  exact omega_equiv_congr (hAB.trans hD.symm)

/-- `ω(pglFinset {k₁}) ∈ Generators 2` (mirrors `omega_pglFinset_mem_Generators_two`, using the
nonempty subset `{k₁}` of `{k₁} ∪ ω{k₁}` instead of `{ω k₁}`). -/
lemma omega_pglFinset_k1_mem_Generators_two :
    omega (pglFinset {minFun 0 zero_lt_omega1}) ∈ Generators 2 := by
  set k1 := minFun 0 zero_lt_omega1 with hk1
  have hcent : pglFinset {k1} ∈ CentBlock {k1} 1 := by
    show pglFinset {k1} ∈ centStep {k1}
    rw [centStep]
    apply Finset.mem_union_right
    rw [Finset.mem_image]
    refine' ⟨{k1}, _, rfl⟩
    unfold nonemptySubsets
    rw [Finset.mem_erase]
    refine ⟨by simp, ?_⟩
    rw [Finset.mem_powerset]
    intro x hx
    simp only [Finset.mem_singleton] at hx
    subst hx
    simp
  have hom : omega (pglFinset {k1}) ∈ omegaImage (CentBlock {k1} 1) :=
    Finset.mem_image_of_mem omega hcent
  rw [Generators_two_eq]
  apply Finset.mem_union_right
  rw [genStep]
  apply Finset.mem_union_left
  apply Finset.mem_union_right
  have hcb : centBase1 0 = {k1} := by
    unfold centBase1; rw [if_pos rfl, dif_pos zero_lt_omega1]
  rw [hcb]
  exact hom

lemma omega_minFun_one_mem_finGl_two (h : (1 : Ordinal.{0}) < omega1) :
    omega (minFun 1 h) ∈ FinGl (Generators 2).toFinFun :=
  finGl_single_of_equiv omega_pglFinset_k1_mem_Generators_two (omega_minFun_one_equiv_gen h)

/-
The literal wedge generator `⋀({ω k₁} ∣ {pgl k₁})` produced by `genStep` lies in
`Generators 2`.
-/
lemma wedgeFinset_gen_mem_Generators_two :
    wedgeFinset [[omega (minFun 0 zero_lt_omega1)]] [pglFinset {minFun 0 zero_lt_omega1}]
      ∈ Generators 2 := by
  rw [Generators_two_eq]
  refine Finset.mem_union_right _ ?_;
  simp +decide only [genStep, CentBlock, centBase1, ↓reduceIte, Finset.union_assoc, Finset.mem_union, Finset.mem_biUnion, Finset.mem_image, Finset.mem_powerset];
  refine Or.inr <| Or.inr <| ⟨ { { ( minFun 0 zero_lt_omega1 ).omega } }, ?_, ?_ ⟩ <;> simp +decide [ nonemptySubsets ];
  · unfold GenBlock; simp +decide [ genBase ] ;
    unfold genStep; simp +decide [ CentBlock, GenBlock ] ;
    unfold omegaImage; simp +decide [ zero_lt_omega1 ] ;
  · refine ⟨ { pglFinset { minFun 0 zero_lt_omega1 } }, ?_, ?_ ⟩ <;> simp +decide [ centStep ];
    unfold omegaImage; simp +decide [ nonemptySubsets ] ;
    exact Or.inr ⟨ { minFun 0 zero_lt_omega1 }, by simp +decide [ zero_lt_omega1 ] ⟩

/-- **`⋁(maxFun 1 ∣ minFun 1) ∈ FinGl (Generators 2)`.**  The wedge of the two level-`1`
generators `maxFun 1` (vertical) and `minFun 1` (diagonal) is equivalent to the literal wedge
generator `⋀({ω k₁} ∣ {pgl k₁}) ∈ Generators 2` (via `wedge_congr_equiv`), hence lies in
`FinGl (Generators 2)`.  Needed for the finite-nonempty `N₁` (wedge) case. -/
lemma wedge_maxFun_minFun_one_mem_finGl_two (h : (1 : Ordinal.{0}) < omega1) :
    wedge (fun _ : Fin 1 => maxFun 1 h) (minFun 1 h) ∈ FinGl (Generators 2).toFinFun := by
  refine finGl_single_of_equiv wedgeFinset_gen_mem_Generators_two ?_
  set k1 := minFun 0 zero_lt_omega1 with hk1
  -- `ω k₁ ≡ maxFun 1 h`
  have hmax : Equiv (maxFun 1 h) (omega k1) := by
    have h1 : ContinuouslyEquiv (omega k1).func (@id ℕ) := omega_minFun_zero_equiv_id zero_lt_omega1
    have h2 : ContinuouslyEquiv (maxFun 1 h).func (@id ℕ) := by
      rw [maxFun_func]; exact maxFun_one_equiv_id
    exact ⟨(h2.trans h1.symm).1, (h2.trans h1.symm).2⟩
  -- `glList [ω k₁] ≡ ω k₁`
  have hv : Equiv (maxFun 1 h) (glList [omega k1]) :=
    hmax.trans (glList_single_equiv (omega k1))
  -- `minFun 1 h ≡ pgl(fun _ => k₁) ≡ pglFinset {k₁} ≡ glList [pglFinset {k₁}]`
  have hpf : pglFinset {k1} = pgl (fun _ => glList [k1]) := by
    unfold pglFinset; simp
  have hD : Equiv (pglFinset {k1}) (pgl (fun _ => k1)) := by
    rw [hpf]; exact pgl_const_equiv_congr (glList_single_equiv k1).symm
  have hd : Equiv (minFun 1 h) (glList [pglFinset {k1}]) :=
    ((minFun_one_equiv_pgl_minFun_zero h).trans hD.symm).trans
      (glList_single_equiv (pglFinset {k1}))
  have := wedge_congr_equiv (n := 1) (v := fun _ : Fin 1 => maxFun 1 h)
    (v' := fun _ : Fin 1 => glList [omega k1]) (d := minFun 1 h) (d' := glList [pglFinset {k1}])
    (fun _ => hv) hd
  simpa [wedgeFinset, wedgeList_eq] using this

/-- **Lower-bound intertwine step for `k₂`.**  Each block's distinguished point `y n` lies in
`IntertwineSet F (minFun 1 h)`: on any clopen `W ∋ y n`, the block keeps its top level, so
`minFun 1 ≤ (F.restrict (A n))` into `W` (`minFun_reduces_into_clopen`), which transports to
`minFun 1 ≤ F.coRestrict W` (`reduces_block_into_coRestrict`). -/
lemma yn_mem_intertwineSet_minFun (h : (1 : Ordinal.{0}) < omega1) (F : ScatFun)
    (A : ℕ → Set ↑F.domain) (y : ℕ → Baire)
    (hrank : ∀ n, CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ n, ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n)
    (n : ℕ) :
    y n ∈ IntertwineSet F (minFun 1 h) := by
  intro V hV
  rw [mem_nhds_iff] at hV
  obtain ⟨V₀, hV₀sub, hV₀open, hV₀y⟩ := hV
  obtain ⟨W, hW_clopen, hyW, hW_sub⟩ :=
    baire_exists_clopen_subset_of_open (y n) V₀ hV₀open hV₀y
  have hne : (CBLevel (F.restrict (A n)).func 1).Nonempty :=
    CBLevel_nonempty_below_rank _ (F.restrict (A n)).hScat 1 (by rw [hrank n]; norm_num)
  obtain ⟨σ1, τ, hσ1, hτ, hred, hval⟩ :=
    minFun_reduces_into_clopen (F.restrict (A n)) 1 h (y n) hne (hdist n) W hW_clopen hyW
  obtain ⟨σ, hσ, hσval, hσfunc⟩ :=
    reduces_block_into_coRestrict F (A n) V₀ (minFun 1 h) σ1 hσ1 (fun z => hW_sub (hval z))
  have hfe : ((F.coRestrict V₀).func ∘ σ) = (fun z => (F.restrict (A n)).func (σ1 z)) :=
    funext hσfunc
  have hred_block : Reduces (minFun 1 h) (F.coRestrict V₀) := by
    refine ⟨σ, hσ, τ, ?_, ?_⟩
    · rw [hfe]; exact hτ
    · intro z; rw [hσfunc z]; exact hred z
  exact hred_block.trans (coRestrict_reduces_of_subset F hV₀sub)

/-- **Lower bound `ω(minFun 1) ≤ F`** (holds for any rank-`2` disjoint union with distinct
distinguished points, independent of `N₁`).  Every `y n ∈ IntertwineSet F (minFun 1)`
(`yn_mem_intertwineSet_minFun`), so that set is infinite and `intertwine_reductions` applies. -/
lemma omega_minFun_one_reduces (h : (1 : Ordinal.{0}) < omega1) (F : ScatFun)
    (A : ℕ → Set ↑F.domain) (y : ℕ → Baire)
    (hy_inj : Function.Injective y)
    (hrank : ∀ n, CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ n, ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n) :
    Reduces (omega (minFun 1 h)) F := by
  set g := minFun 1 h with hg
  have hsub : Set.range y ⊆ IntertwineSet F g :=
    fun _ ⟨n, hn⟩ => hn ▸ yn_mem_intertwineSet_minFun h F A y hrank hdist n
  have hInf : (IntertwineSet F g).Infinite :=
    (Set.infinite_range_of_injective hy_inj).mono hsub
  have h1 := intertwine_reductions F (fun _ : Fin 1 => g) (fun _ => hInf)
  exact (omega_equiv_congr (glFin_single_equiv g)).2.trans h1

/-
**Upper bound `F ≤ ω(minFun 1)`** when each block `≤ minFun 1 ⊕ maxFun 1`.  Then
`F ≤ gl blocks ≤ ω(minFun 1 ⊕ maxFun 1) ≤ ω(minFun 1 ⊕ minFun 1) ≡ ω(minFun 1)`, using
`maxFun_one_reduces_minFun_one` and the `2 → 1` reindexing `omega_glFin_reduces_reindex`.
-/
lemma reduces_F_omega_minFun_one (h : (1 : Ordinal.{0}) < omega1) (F : ScatFun)
    (A : ℕ → Set ↑F.domain) (hdu : F.IsDisjointUnion A)
    (hblock : ∀ n, Reduces (F.restrict (A n)) (minFun 1 h ⊕ maxFun 1 h)) :
    Reduces F (omega (minFun 1 h)) := by
  -- By `scatFun_reduces_gl_of_domain_partition` and `gl_reduces_of_pointwise`, we get
  have hF_le_omega : F.Reduces (ScatFun.omega (minFun 1 h ⊕ maxFun 1 h)) :=
    (scatFun_reduces_gl_of_domain_partition F A hdu).trans (gl_reduces_of_pointwise _ _ hblock)
  -- By `maxFun_one_reduces_minFun_one`, we get `minFun 1 h ⊕ maxFun 1 h ≤ minFun 1 h ⊕ minFun 1 h`.
  have h_minFun1_maxFun1_le_minFun1_minFun1 : (minFun 1 h ⊕ maxFun 1 h).Reduces (minFun 1 h ⊕ minFun 1 h) := by
    apply_rules [ gl_reduces_of_pointwise ];
    intro i; rcases i with ( _ | _ | i ) <;> simp +decide [ copiesSeq ] ;
    · exact .refl _;
    · exact maxFun_one_reduces_minFun_one h;
    · simp +decide [ copiesList ];
      simp +decide only [List.finRange, List.ofFn_succ, Fin.isValue, Fin.succ_zero_eq_one, List.ofFn_zero, List.flatMap_cons, Matrix.cons_val_zero, List.replicate_one, Matrix.cons_val_one, Matrix.cons_val_fin_one, List.flatMap_nil, List.append_nil, List.cons_append, List.nil_append, List.length_cons, List.length_nil, zero_add, Nat.reduceAdd, not_lt, le_add_iff_nonneg_left, zero_le, getElem?_neg, Option.getD_none];
      grind [empty_reduces];
  -- By `omega_reduces_of_reduces`, we get `omega (minFun 1 h ⊕ maxFun 1 h) ≤ omega (minFun 1 h ⊕ minFun 1 h)`.
  have h_omega_minFun1_maxFun1_le_omega_minFun1_minFun1 : (ScatFun.omega (minFun 1 h ⊕ maxFun 1 h)).Reduces (ScatFun.omega (minFun 1 h ⊕ minFun 1 h)) := by
    apply gl_reduces_of_pointwise;
    exact fun _ => h_minFun1_maxFun1_le_minFun1_minFun1;
  -- By `omega_glFin_reduces_reindex`, we get `omega (minFun 1 h ⊕ minFun 1 h) ≤ omega (minFun 1 h)`.
  have h_omega_minFun1_minFun1_le_omega_minFun1 : (ScatFun.omega (minFun 1 h ⊕ minFun 1 h)).Reduces (ScatFun.omega (minFun 1 h)) := by
    have h_omega_minFun1_minFun1_le_omega_minFun1 : (ScatFun.omega (ScatFun.glFin (fun _ : Fin 2 => minFun 1 h))).Reduces (ScatFun.omega (minFun 1 h)) := by
      convert ScatFun.omega_glFin_reduces_reindex _ _ _ using 1;
      exact fun n => if n % 2 = 0 then 0 else 1;
      exact fun k N => ⟨ 2 * N + k, by linarith, by fin_cases k <;> simp +decide [ Nat.add_mod ] ⟩;
    convert h_omega_minFun1_minFun1_le_omega_minFun1 using 1;
    unfold ScatFun.glFin;
    congr! 1;
    convert ScatFun.Gl_eq_glList_copiesList _ _ using 1;
    unfold copiesList; simp +decide [ glList ] ;
    congr! 1;
    ext ( _ | _ | k ) <;> simp +decide [ List.finRange ];
  exact hF_le_omega.trans ( h_omega_minFun1_maxFun1_le_omega_minFun1_minFun1.trans h_omega_minFun1_minFun1_le_omega_minFun1 )

/-
**`ω(minFun 1 ⊕ maxFun 1) ≤ ω(minFun 1)`** (the `λ = 1` analogue of
`omega_glBin_minFun_maxFun_reduces_omega_minFun`, which needs `λ` limit; here we use the concrete
bound `maxFun 1 ≤ minFun 1`).
-/
lemma omega_glBin_minFun_maxFun_one_reduces (h : (1 : Ordinal.{0}) < omega1) :
    Reduces (omega (minFun 1 h ⊕ maxFun 1 h)) (omega (minFun 1 h)) := by
  have h_omega_minFun1_maxFun1_le_omega_minFun1_minFun1 : Reduces (omega (minFun 1 h ⊕ maxFun 1 h)) (omega (minFun 1 h ⊕ minFun 1 h)) := by
    apply omega_reduces_of_reduces;
    apply glBin_reduces_of_reduces;
    · constructor;
      exact ⟨ continuous_id, fun x => x, continuousOn_id, fun x => rfl ⟩;
    · exact maxFun_one_reduces_minFun_one h
  have h_omega_minFun1_minFun1_le_omega_minFun1 : Reduces (omega (minFun 1 h ⊕ minFun 1 h)) (omega (minFun 1 h)) := by
    convert omega_glFin_reduces_reindex _ _ _;
    rotate_left;
    rotate_left;
    exact 2;
    exact fun _ => minFun 1 h;
    exact fun n => if n % 2 = 0 then 0 else 1;
    · exact fun k N => ⟨ 2 * N + k, by linarith, by fin_cases k <;> simp +decide [ Nat.add_mod ] ⟩;
    · simp +decide [ glFin, Gl ];
      congr with x ; simp +decide [ copiesSeq ];
      rcases x with ( _ | _ | x ) <;> simp +decide [ copiesList ];
      · rfl;
      · rfl;
      · simp +decide [ List.finRange, List.flatMap ];
    · exact (congrArg omega ∘ congrArg (minFun 1)) rfl
  exact h_omega_minFun1_maxFun1_le_omega_minFun1_minFun1.trans h_omega_minFun1_minFun1_le_omega_minFun1

/-- **Case `N₁` empty** (`5_precise_struct_memo.tex:397-400`), specialised to `lam = 1`: every
block is `≡ minFun 1 h` or `≡ minFun 1 h ⊕ maxFun 1 h`, both `≤ minFun 1 h ⊕ maxFun 1 h ≤
2 • minFun 1 h`, giving `F ≡ ω (minFun 1 h)`.

## Provided solution

Identical strategy to `LambdaPlusOne.lean`'s `case_N1_empty`:
* `ω (minFun 1 h) ≤ F` from `Minfunctions`/`minFun_is_minimum`
  (`PointedGluing/MinFun/Theorems.lean:573`) applied at each `y n` plus `intertwine_reductions`
  (does not need `N₁` empty).
* `F ≤ gl (fun n => F.restrict (A n))` always
  (`scatFun_reduces_gl_of_domain_partition`); since `N₁ = ∅`, every block is `≤ minFun 1 h ⊕
  maxFun 1 h`, so `gl (blocks) ≤ ω (minFun 1 h ⊕ maxFun 1 h)` by `gl_reduces_of_pointwise`.
* The bound `maxFun 1 h ≤ minFun 1 h` (i.e. `ℓ_1 ≤ k_2`) is supplied here by
  `maxFun_one_reduces_minFun_one`: `general_structure_theorem`'s successor clause does not apply
  at `η = 0, n = 1` (it would need `CBRank (minFun 1 h).func ≥ 3`), but the `λ = 1` base case is
  concrete — `ℓ_1 = ω·pgl(∅) = ω(k_1)` (a plain gluing of copies of `k_1`) reduces into
  `k_2 = pgl(k_1)` (their pointed gluing) via `gl_reduces_pgl_direct`.  These two steps are packaged
  in `reduces_F_omega_minFun_one` (upper bound) together with the `2 → 1` reindexing.
* Combining, `F ≡ ω (minFun 1 h)`.  Since `ω (minFun 1 h) ≡ ω (pglFinset {k₁})` with
  `pglFinset {k₁} ∈ CentBlock {k₁} 1` (`k₂ ≡ pgl(k₁)`), we get `ω (minFun 1 h) ∈ Generators 2`
  (`omega_minFun_one_mem_finGl_two`), giving `FinGl` membership as in `case_N1_infinite_two`. -/
theorem case_N1_empty_two (h : (1 : Ordinal.{0}) < omega1)
    (F : ScatFun) (A : ℕ → Set ↑F.domain) (hdu : F.IsDisjointUnion A)
    (y : ℕ → Baire) (hy_inj : Function.Injective y)
    (hrank : ∀ n, CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ n, ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n)
    (hN1_empty : {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)} = ∅) :
    F ∈ FinGl (Generators 2).toFinFun := by
  have hlow : Reduces (omega (minFun 1 h)) F :=
    omega_minFun_one_reduces h F A y hy_inj hrank hdist
  have hblock : ∀ n, Reduces (F.restrict (A n)) (minFun 1 h ⊕ maxFun 1 h) := by
    intro n
    rcases block_classified h F A y n (hrank n) (hdist n) with hc | hc | hc
    · exact hc.1.trans (minFun_one_le_glBin h)
    · exact hc.1
    · exfalso
      have hmem : n ∈ {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)} := hc
      rw [hN1_empty] at hmem
      exact hmem
  have hup : Reduces F (omega (minFun 1 h)) :=
    reduces_F_omega_minFun_one h F A hdu hblock
  exact finGl_closed_equiv _ (omega_minFun_one_mem_finGl_two h) ⟨hlow, hup⟩

/- **Case `N₁` finite and non-empty** (`5_precise_struct_memo.tex:401-422`), specialised to
`lam = 1`: the case where the wedge operation genuinely enters. Two sub-cases, on whether some
clopen `U ⊇ Y₁ := y '' N₁` still excludes infinitely many `n ∈ N₀ := ℕ ∖ N₁`.

## Provided solution

Identical strategy to `LambdaPlusOne.lean`'s `case_N1_finite_nonempty`:
* **Sub-case (a)**: some clopen `U ⊇ Y₁` has `{n ∈ N₀ | y n ∉ U}` infinite. Then
  `ω (minFun 1 h) ≤ F.coRestrict Uᶜ` and `|N₁| • succMaxFun 1 h ≤ F.coRestrict U` (centeredness
  of `succMaxFun 1 h` + `Gluingaslowerbound`), so gluing via `Gluingasupperbound`/
  `Gluingaslowerbound` (`ContinuousReducibility/Gluing/UpperBound.lean:340`
  `clopen_partition_to_gluing_reduces`, `disjoint_union_reduces_gluing`) gives
  `F ≡ (|N₁| • succMaxFun 1 h) ⊕ ω (minFun 1 h)`, a finite gluing of the two generators
  `succMaxFun 1 h`, `minFun 1 h` (both in `Generators 2`).
* **Sub-case (b)**: every clopen `U ⊇ Y₁` contains all but finitely many `y n` (`n ∈ N₀`). Choose
  pairwise disjoint clopen `Uᵢ ∋ yᵢ` (`i ∈ N₁`, finite) with fibres `Pᵢ = {n | y n ∈ Uᵢ}` each
  infinite or `= {i}`. For `Pᵢ = {i}`, `F.restrict (A i) ≡ succMaxFun 1 h ≤ F.coRestrict Uᵢ`
  directly. For `Pᵢ` infinite, `F.restrict (⋃_{n ∈ Pᵢ} A n)` falls under `diagonal_for_lambda_plus_one`
  (`ScatFun/PreciseStructure/DiagonalForLambdaPlusOne.lean:786`, fully proved, instantiated at
  `lam = 1`): it reduces to `wedge (fun _ : Fin 1 => maxFun 1 h) (minFun 1 h) ≤ F.coRestrict Uᵢ`.
  Assembling over the finite `N₁` gives `F` a finite gluing of `succMaxFun 1 h` and
  `wedge (fun _ => maxFun 1 h) (minFun 1 h)` — the latter literally in `Generators 2` (the
  `genStep`-produced wedge term with vertical `{maxFun 1 h}` and diagonal `{minFun 1 h}`, per the
  note in `Generators_two_finitely_generates_of_finite_degree`'s docstring above) — giving
  `F ∈ FinGl (Generators 2).toFinFun`.

Both sub-cases reuse the finite-clopen-partition bookkeeping of `diagonal_for_lambda_plus_one`'s
supporting lemmas in `DiagonalForLambdaPlusOne.lean`; adapting them to the present two-level case
split (rather than that file's single fixed diagonal point `y 0`) is the main remaining work. -/
/-! ### The finite-`CB`-degree case (assembly)

Each simple rank-`2` piece is classified by `block_classified`/`simpleFunctionsLambdaPlusOne`
as one of `minFun 1`, `minFun 1 ⊕ maxFun 1`, `succMaxFun 1`; these are identified with literal
members of `Generators 2` (`pglFinset {k₁}`, `omega k₁`, `pglFinset {ω k₁}`). -/

/-- Literal membership: `pglFinset {k₁} ∈ Generators 2` (`pglFinset {k₁} ∈ CentBlock {k₁} 1 =
`the `Cn` argument of the outer `genStep`, which is a sub-union of `Generators 2`). -/
lemma pglFinset_k1_mem_Generators_two :
    pglFinset {minFun 0 zero_lt_omega1} ∈ Generators 2 := by
  set k1 := minFun 0 zero_lt_omega1 with hk1
  have hcent : pglFinset {k1} ∈ CentBlock {k1} 1 := by
    show pglFinset {k1} ∈ centStep {k1}
    rw [centStep]
    apply Finset.mem_union_right
    rw [Finset.mem_image]
    refine' ⟨{k1}, _, rfl⟩
    unfold nonemptySubsets
    rw [Finset.mem_erase]
    refine ⟨by simp, ?_⟩
    rw [Finset.mem_powerset]
    intro x hx
    simp only [Finset.mem_singleton] at hx
    subst hx
    simp
  rw [Generators_two_eq]
  apply Finset.mem_union_right
  rw [genStep]
  apply Finset.mem_union_left
  apply Finset.mem_union_left
  have hcb : centBase1 0 = {k1} := by
    unfold centBase1; rw [if_pos rfl, dif_pos zero_lt_omega1]
  rw [hcb]
  exact hcent

/-- Literal membership: `ω k₁ ∈ Generators 2` (`k₁ ∈ CentBlock {k₁} 1`, so `ω k₁ ∈ omegaImage`
of it, a sub-union of the outer `genStep`). -/
lemma omega_k1_mem_Generators_two :
    omega (minFun 0 zero_lt_omega1) ∈ Generators 2 := by
  set k1 := minFun 0 zero_lt_omega1 with hk1
  have hk1mem : k1 ∈ CentBlock {k1} 1 :=
    CentBlock_subset_succ _ 0 (Finset.mem_singleton_self _)
  rw [Generators_two_eq]
  apply Finset.mem_union_right
  rw [genStep]
  apply Finset.mem_union_left
  apply Finset.mem_union_right
  have hcb : centBase1 0 = {k1} := by
    unfold centBase1; rw [if_pos rfl, dif_pos zero_lt_omega1]
  rw [hcb]
  exact Finset.mem_image_of_mem omega hk1mem

/-- Literal membership: `pglFinset {ω k₁} ∈ Generators 2` (as in
`omega_pglFinset_mem_Generators_two`, but the un-`ω`'d element). -/
lemma pglFinset_omega_k1_mem_Generators_two :
    pglFinset {omega (minFun 0 zero_lt_omega1)} ∈ Generators 2 := by
  set k1 := minFun 0 zero_lt_omega1 with hk1
  have hcent : pglFinset {omega k1} ∈ CentBlock {k1} 1 := by
    show pglFinset {omega k1} ∈ centStep {k1}
    rw [centStep]
    apply Finset.mem_union_right
    rw [Finset.mem_image]
    refine' ⟨{omega k1}, _, rfl⟩
    unfold nonemptySubsets
    rw [Finset.mem_erase]
    refine ⟨by simp, ?_⟩
    rw [Finset.mem_powerset]
    intro x hx
    simp only [Finset.mem_singleton] at hx
    subst hx
    simp [omegaImage]
  rw [Generators_two_eq]
  apply Finset.mem_union_right
  rw [genStep]
  apply Finset.mem_union_left
  apply Finset.mem_union_left
  have hcb : centBase1 0 = {k1} := by
    unfold centBase1; rw [if_pos rfl, dif_pos zero_lt_omega1]
  rw [hcb]
  exact hcent

/-- `minFun 1 ≡ pglFinset {k₁}` (`minFun 1 ≡ pgl(fun _ ↦ k₁) ≡ pglFinset {k₁}`). -/
lemma minFun_one_equiv_pglFinset_k1 (h : (1 : Ordinal.{0}) < omega1) :
    Equiv (minFun 1 h) (pglFinset {minFun 0 zero_lt_omega1}) := by
  set k1 := minFun 0 zero_lt_omega1 with hk1
  have hpf : pglFinset {k1} = pgl (fun _ => glList [k1]) := by unfold pglFinset; simp
  have hD : Equiv (pglFinset {k1}) (pgl (fun _ => k1)) := by
    rw [hpf]; exact pgl_const_equiv_congr (glList_single_equiv k1).symm
  exact (minFun_one_equiv_pgl_minFun_zero h).trans hD.symm

/-- `maxFun 1 ≡ ω k₁` (both act as the identity on their domain). -/
lemma maxFun_one_equiv_omega_k1 (h : (1 : Ordinal.{0}) < omega1) :
    Equiv (maxFun 1 h) (omega (minFun 0 zero_lt_omega1)) := by
  have h1 : ContinuouslyEquiv (omega (minFun 0 zero_lt_omega1)).func (@id ℕ) :=
    omega_minFun_zero_equiv_id zero_lt_omega1
  have h2 : ContinuouslyEquiv (maxFun 1 h).func (@id ℕ) := by
    rw [maxFun_func]; exact maxFun_one_equiv_id
  exact ⟨(h2.trans h1.symm).1, (h2.trans h1.symm).2⟩

/-- `succMaxFun 1 ≡ pglFinset {ω k₁}` (the level-1 `succMaxFun` identification). -/
lemma succMaxFun_one_equiv_pglFinset_omega_k1 (h : (1 : Ordinal.{0}) < omega1) :
    Equiv (succMaxFun 1 h) (pglFinset {omega (minFun 0 zero_lt_omega1)}) := by
  set k1 := minFun 0 zero_lt_omega1 with hk1
  have hA : Equiv (omega k1) (maxFun 1 h) := (maxFun_one_equiv_omega_k1 h).symm
  have hpf : pglFinset {omega k1} = pgl (fun _ => glList [omega k1]) := by
    unfold pglFinset; simp
  have hD : Equiv (pglFinset {omega k1}) (pgl (fun _ => omega k1)) := by
    rw [hpf]; exact pgl_const_equiv_congr (glList_single_equiv (omega k1)).symm
  have hB : Equiv (pgl (fun _ => omega k1)) (succMaxFun 1 h) := by
    have hbb := pgl_const_equiv_congr hA
    rwa [← succMaxFun_eq] at hbb
  exact (hD.trans hB).symm

/-- **`succMaxFun 1 h ∈ FinGl (Generators 2)`.**  Raw (not `ω`-wrapped) version of
`omega_succMaxFun_one_mem_finGl_two`, via the same `pglFinset {ω k₁}` literal member. Needed for
sub-case (b)'s singleton-fibre classes. -/
lemma succMaxFun_one_mem_finGl_two (h : (1 : Ordinal.{0}) < omega1) :
    succMaxFun 1 h ∈ FinGl (Generators 2).toFinFun :=
  finGl_single_of_equiv pglFinset_omega_k1_mem_Generators_two
    (succMaxFun_one_equiv_pglFinset_omega_k1 h)

/-- **Classification of an isolated rank-`2` corestriction as a `glList` of `Generators 2`
members.**  `λ = 1` analogue of `Fb_isolated_glList` (`LambdaPlusOne.lean`): the corestriction
of `F` to a clopen codomain piece `C` containing exactly one top-level image point `s` is simple
of rank `2`, hence (via `simpleFunctionsLambdaPlusOne` at `lam = 1`) equivalent to one of the
three level-`1` generators, each equivalent to a literal member of `Generators 2`. -/
lemma Fb_isolated_glList_two (h : (1 : Ordinal.{0}) < omega1)
    (F : ScatFun) (hFrank : CBRank F.func = 2)
    (C : Set Baire) (hC : IsClopen C) (s : Baire) (hsC : s ∈ C)
    (htop : ∃ x, x ∈ CBLevel F.func 1 ∧ F.func x = s)
    (hother : ∀ x, x ∈ CBLevel F.func 1 → F.func x ∈ C → F.func x = s) :
    ∃ L : List ScatFun, (∀ w ∈ L, w ∈ Generators 2) ∧
      Equiv (coRestrict F C) (glList L) := by
  have hFrank' : CBRank F.func = 1 + 1 := by rw [hFrank]; norm_num
  obtain ⟨hrank, hconst⟩ := coRestrict_isolated_rank_const 1 F hFrank' C hC s hsC htop hother
  have hsimple : SimpleFun (coRestrict F C).func :=
    simpleFun_of_rank_of_const (coRestrict F C) 1 hrank s hconst
  rcases simpleFunctionsLambdaPlusOne 1 h (Or.inl rfl) twoBQO_levelLT_one
      (coRestrict F C) hrank hsimple with hc | hc | hc
  · refine ⟨[pglFinset {minFun 0 zero_lt_omega1}], ?_, ?_⟩
    · intro w hw; simp only [List.mem_singleton] at hw; subst hw
      exact pglFinset_k1_mem_Generators_two
    · exact (hc.trans (minFun_one_equiv_pglFinset_k1 h)).trans (glList_single_equiv _)
  · refine ⟨[pglFinset {minFun 0 zero_lt_omega1}, omega (minFun 0 zero_lt_omega1)], ?_, ?_⟩
    · intro w hw; simp only [List.mem_cons, List.not_mem_nil, or_false] at hw
      rcases hw with rfl | rfl
      · exact pglFinset_k1_mem_Generators_two
      · exact omega_k1_mem_Generators_two
    · have hbin : Equiv (minFun 1 h ⊕ maxFun 1 h)
          (pglFinset {minFun 0 zero_lt_omega1} ⊕ omega (minFun 0 zero_lt_omega1)) :=
        glBin_congr (minFun_one_equiv_pglFinset_k1 h) (maxFun_one_equiv_omega_k1 h)
      exact (hc.trans hbin).trans (finGl_glBin_equiv_glList _ _)
  · refine ⟨[pglFinset {omega (minFun 0 zero_lt_omega1)}], ?_, ?_⟩
    · intro w hw; simp only [List.mem_singleton] at hw; subst hw
      exact pglFinset_omega_k1_mem_Generators_two
    · exact (hc.trans (succMaxFun_one_equiv_pglFinset_omega_k1 h)).trans (glList_single_equiv _)

/-- **Finite-degree functions of `CB`-rank `2` are finitely generated** (memoir Corollary
`finitedegreedamuddafuckaz`, `λ = 1` instance).  `λ = 1` analogue of
`Generators_lambdaPlusOne_finitely_generates_of_finite_degree`. -/
theorem Generators_two_finitely_generates_of_finite_degree :
    ∀ F : ScatFun, CBRank F.func = 2 → (F.func '' CBLevel F.func 1).Finite →
      F ∈ FinGl (Generators 2).toFinFun := by
  intro F hFrank hSfin
  classical
  set S : Finset Baire := hSfin.toFinset with hSdef
  have hlevelne : (CBLevel F.func 1).Nonempty :=
    CBLevel_nonempty_below_rank F.func F.hScat 1 (by rw [hFrank]; norm_num)
  have hSne : S.Nonempty := by
    obtain ⟨x, hx⟩ := hlevelne
    exact ⟨F.func x, by rw [hSdef, Set.Finite.mem_toFinset]; exact ⟨x, hx, rfl⟩⟩
  obtain ⟨assign, hassign_cont, hassign_lt, hassign_inj, hassign_surj⟩ :=
    exists_isolating_assign S hSne
  set B : ℕ → Set Baire := fun i => {x | assign x = i} with hBdef
  have hB_clopen : ∀ i, IsClopen (B i) := by
    intro i
    have hpre : B i = assign ⁻¹' {i} := rfl
    rw [hpre]
    exact ⟨(isClosed_discrete _).preimage hassign_cont,
      (isOpen_discrete _).preimage hassign_cont⟩
  have hB_disj : ∀ i j, i ≠ j → Disjoint (B i) (B j) := by
    intro i j hij
    rw [Set.disjoint_left]; intro x hx hx'
    exact hij (hx.symm.trans hx')
  have hB_cover : ⋃ i, B i = Set.univ := by
    ext x; simp only [Set.mem_iUnion, Set.mem_univ, iff_true]; exact ⟨assign x, rfl⟩
  have hclass : ∀ i : Fin S.card, ∃ L : List ScatFun,
      (∀ w ∈ L, w ∈ Generators 2) ∧ Equiv (coRestrict F (B i.val)) (glList L) := by
    intro i
    obtain ⟨s, hsS, hsi⟩ := hassign_surj i.val i.isLt
    have hsC : s ∈ B i.val := hsi
    have hsimg : s ∈ (F.func '' CBLevel F.func 1) :=
      (hSdef ▸ Set.Finite.mem_toFinset hSfin).mp hsS
    obtain ⟨x0, hx0lev, hx0⟩ := hsimg
    have hother : ∀ x, x ∈ CBLevel F.func 1 → F.func x ∈ B i.val → F.func x = s := by
      intro x hxlev hxB
      have hfxS : F.func x ∈ S := by
        rw [hSdef, Set.Finite.mem_toFinset]; exact ⟨x, hxlev, rfl⟩
      have heq : assign (F.func x) = assign s := by
        have : assign (F.func x) = i.val := hxB
        rw [this, hsi]
      exact hassign_inj (Finset.mem_coe.mpr hfxS) (Finset.mem_coe.mpr hsS) heq
    exact Fb_isolated_glList_two one_lt_omega1 F hFrank
      (B i.val) (hB_clopen i.val) s hsC ⟨x0, hx0lev, hx0⟩ hother
  choose Lf hLf_mem hLf_eq using hclass
  have hequiv : ∀ i, ContinuouslyEquiv (CoRestrict' F.domain F.func (B i))
      ((fun i : ℕ => if h : i < S.card then glList (Lf ⟨i, h⟩) else empty) i).func := by
    intro i
    simp only []
    by_cases h : i < S.card
    · rw [dif_pos h]; exact hLf_eq ⟨i, h⟩
    · rw [dif_neg h]
      have hFbEmpty : IsEmpty ↑(coRestrict F (B i)).domain := by
        constructor
        rintro ⟨x, hxdom, hmem⟩
        have hyi : assign (F.func ⟨x, hxdom⟩) = i := hmem
        have := hassign_lt (F.func ⟨x, hxdom⟩); omega
      exact ⟨reduces_of_isEmpty_domain hFbEmpty, empty_reduces (coRestrict F (B i))⟩
  have hFgl : Equiv F
      (gl (fun i : ℕ => if h : i < S.card then glList (Lf ⟨i, h⟩) else empty)) :=
    equiv_gl_of_codomain_clopen_partition F _ B hB_clopen hB_disj hB_cover hequiv
  have hflat := gl_dite_glList_flatten_equiv S.card Lf
  refine finGl_of_equiv_glList ?_ ⟨hFgl.1.trans hflat.1, hflat.2.trans hFgl.2⟩
  intro w hw
  rw [List.mem_flatMap] at hw
  obtain ⟨i, _, hwi⟩ := hw
  exact hLf_mem i w hwi

/-
**Sub-case (a)** of `case_N1_finite_nonempty_two` (`lam = 1`): there is a clopen `U ⊇ Y₁` with
infinitely many `N₀`-blocks landing outside `U`.  Then `F ≡ |N₁| • succMaxFun 1 ⊕ ω (minFun 1)`.
-/
theorem case_N1_finite_nonempty_subcase_a_two (h : (1 : Ordinal.{0}) < omega1)
    (F : ScatFun) (A : ℕ → Set ↑F.domain) (hdu : F.IsDisjointUnion A)
    (y : ℕ → Baire) (hy_inj : Function.Injective y)
    (hrank : ∀ n, CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ n, ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n)
    (hN1_fin : {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}.Finite)
    (_hN1_ne : {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}.Nonempty)
    (hU : ∃ U : Set Baire, IsClopen U ∧
      (∀ n, Equiv (F.restrict (A n)) (succMaxFun 1 h) → y n ∈ U) ∧
      {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∉ U}.Infinite) :
    F ∈ FinGl (Generators 2).toFinFun := by
  obtain ⟨U, hUcl, hUsub, hUinf⟩ := hU
  set I := hN1_fin.toFinset
  set T := (glList (List.replicate I.card (succMaxFun 1 h))) ⊕ omega (minFun 1 h);
  have h_equiv : Equiv F T := by
    have h_upper : Reduces F T := by
      have h_upper : Reduces F (gl (fun n => F.restrict (A n))) := by
        exact scatFun_reduces_gl_of_domain_partition F A hdu
      have h_upper : Reduces (gl (fun n => F.restrict (A n))) (glBin (glList (List.replicate I.card (succMaxFun 1 h))) (omega (minFun 1 h ⊕ maxFun 1 h))) := by
        apply reduces_gl_glBin_replicate_omega;
        · exact fun n hn => ( hN1_fin.mem_toFinset.mp hn ).1;
        · intro n hnI;
          have := block_classified h F A y n ( hrank n ) ( hdist n );
          rcases this with ( h | h | h ) <;> simp_all +decide [ ScatFun.Equiv ];
          · exact h.1.trans ( minFun_one_le_glBin _ );
          · exact False.elim <| hnI <| hN1_fin.mem_toFinset.mpr h;
      have h_upper : Reduces (glList (List.replicate I.card (succMaxFun 1 h)) ⊕ (minFun 1 h ⊕ maxFun 1 h).omega) (glList (List.replicate I.card (succMaxFun 1 h)) ⊕ (minFun 1 h).omega) := by
        apply glBin_reduces_of_reduces;
        · constructor;
          exact ⟨ continuous_id, fun x => x, continuousOn_id, fun x => rfl ⟩;
        · exact omega_glBin_minFun_maxFun_one_reduces h;
      exact .trans ‹_› ( .trans ‹_› ‹_› );
    have h_lower : Reduces (glList (List.replicate I.card (succMaxFun 1 h))) (F.coRestrict U) := by
      have h_lower : Reduces (glList (List.replicate I.card (succMaxFun 1 h))) (F.coRestrict U) := by
        have h_intertwine : ∀ n ∈ I, y n ∈ IntertwineSet F (succMaxFun 1 h) := by
          intros n hnI
          apply yn_mem_intertwineSet h F A hdu y hdist n (hrank n) (hN1_fin.mem_toFinset.mp hnI)
        convert glList_replicate_reduces_coRestrict_of_intertwine F ( succMaxFun 1 h ) U hUcl ( I.image y ) _ _ using 1;
        · rw [ Finset.card_image_of_injective _ hy_inj ];
        · aesop_cat;
        · aesop;
      exact h_lower
    have h_lower' : Reduces (omega (minFun 1 h)) (F.coRestrict Uᶜ) := by
      apply omega_reduces_of_intertwineSet_infinite;
      refine Set.Infinite.mono ?_ ( hUinf.image hy_inj.injOn );
      intro x hx
      obtain ⟨n, hn, rfl⟩ := hx;
      apply mem_intertwineSet_coRestrict_of_open;
      · exact hUcl.isClosed.isOpen_compl;
      · exact hn.2;
      · apply yn_mem_intertwineSet_minFun h F A y hrank hdist n
    have h_lower'' : Reduces T F := by
      exact glBin_reduces_of_reduces h_lower h_lower' |> fun h => h.trans ( glBin_coRestrict_compl_reduces F U hUcl )
    exact ⟨h_upper, h_lower''⟩;
  apply finGl_closed_equiv (B := (Generators 2).toFinFun) (hf := ?_) (h := h_equiv.symm);
  apply finGl_glBin_mem;
  · grind [finGl_glList_replicate_mem, succMaxFun_one_mem_finGl_two];
  · exact omega_minFun_one_mem_finGl_two h

/-- **Sub-case (b)** of `case_N1_finite_nonempty_two` (`lam = 1`): every clopen `U ⊇ Y₁` contains
all but finitely many `N₀`-distinguished points.  Then `F` is a finite gluing of `succMaxFun 1` and
the wedge generator `⋁(maxFun 1 ∣ minFun 1)`, via `diagonal_for_lambda_plus_one`. -/
theorem case_N1_finite_nonempty_subcase_b_two (h : (1 : Ordinal.{0}) < omega1)
    (F : ScatFun) (A : ℕ → Set ↑F.domain) (hdu : F.IsDisjointUnion A)
    (y : ℕ → Baire) (hy_inj : Function.Injective y)
    (hrank : ∀ n, CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ n, ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n)
    (hN1_fin : {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}.Finite)
    (_hN1_ne : {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}.Nonempty)
    (hU : ∀ U : Set Baire, IsClopen U →
      (∀ n, Equiv (F.restrict (A n)) (succMaxFun 1 h) → y n ∈ U) →
      {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∉ U}.Finite) :
    F ∈ FinGl (Generators 2).toFinFun := by
  set I := hN1_fin.toFinset with hIdef
  obtain ⟨K, hiso, hdisj⟩ := exists_uniform_isolating_or_infinite_clopen y hy_inj I
  set U : ℕ → Set Baire := fun i => nbhd (y i) K with hUdef
  have hUcl : ∀ i, IsClopen (U i) := fun i => baire_nbhd_isClopen (y i) K
  have hUmem : ∀ i, y i ∈ U i := fun i j _ => rfl
  set Ubig : Set Baire := ⋃ i ∈ I, U i with hUbigdef
  have hUbigcl : IsClopen Ubig := isClopen_biUnion_finset (fun i _ => hUcl i)
  have hUbigsub : ∀ n, Equiv (F.restrict (A n)) (succMaxFun 1 h) → y n ∈ Ubig := by
    intro n hn
    exact Set.mem_biUnion (hN1_fin.mem_toFinset.mpr hn) (hUmem n)
  have hL : {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∉ Ubig}.Finite :=
    hU Ubig hUbigcl hUbigsub
  -- N₀ is cofinite in ℕ, hence infinite.
  have hN0_inf : {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h)}.Infinite := by
    have hcompl : {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h)} = (↑I : Set ℕ)ᶜ := by
      ext n
      simp only [Set.mem_setOf_eq, Set.mem_compl_iff, Finset.mem_coe]
      rw [hIdef, hN1_fin.mem_toFinset, Set.mem_setOf_eq]
    rw [hcompl]
    exact (Finset.finite_toSet I).infinite_compl
  -- Removing the (finite) stragglers, infinitely many N₀-points land inside `Ubig`.
  have hN0_in_Ubig_inf :
      {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∈ Ubig}.Infinite := by
    have heq : {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h)} \
        {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∉ Ubig} =
        {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∈ Ubig} := by
      ext n
      simp only [Set.mem_diff, Set.mem_setOf_eq]
      tauto
    rw [← heq]
    exact hN0_inf.diff hL
  -- Pigeonhole over the finite index set `I`: some `U i₀` catches infinitely many N₀-points.
  obtain ⟨i₀, hi₀I, hi₀inf⟩ :
      ∃ i ∈ I, {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∈ U i}.Infinite := by
    by_contra hcon
    push_neg at hcon
    have hall_fin : ∀ i ∈ I,
        {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∈ U i}.Finite :=
      fun i hi => hcon i hi
    apply hN0_in_Ubig_inf
    have hsub : {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∈ Ubig} ⊆
        ⋃ i ∈ I, {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∈ U i} := by
      rintro n ⟨hnE, hnU⟩
      obtain ⟨i, hi, hyi⟩ := Set.mem_iUnion₂.mp hnU
      exact Set.mem_biUnion hi ⟨hnE, hyi⟩
    exact (Set.Finite.biUnion (Finset.finite_toSet I) hall_fin).subset hsub
  -- The infinite branch holds at `i₀`, and every point it catches beyond `i₀` itself is in N₀.
  have hPi0_inf : {n | y n ∈ U i₀}.Infinite :=
    Set.Infinite.mono (fun n hn => hn.2) hi₀inf
  -- Partition `ℕ` by folding the leftover stragglers `R` into `P i₀`.
  set P : ℕ → Set ℕ := fun i => {n | y n ∈ U i} with hPdef
  set R : Set ℕ := {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∉ Ubig} with hRdef
  set P' : ℕ → Set ℕ := fun i => if i = i₀ then P i₀ ∪ R else P i with hP'def
  have hP_disj : ∀ i ∈ I, ∀ j ∈ I, i ≠ j → Disjoint (P i) (P j) := by
    intro i hi j hj hij
    rw [Set.disjoint_left]
    intro n hnPi hnPj
    exact (Set.disjoint_left.mp (hdisj i hi j hj hij) hnPi) hnPj
  have hR_disj_P : ∀ j ∈ I, Disjoint R (P j) := by
    intro j hj
    rw [Set.disjoint_left]
    intro n hnR hnPj
    exact hnR.2 (Set.mem_biUnion hj hnPj)
  have hP'_pairwiseDisjoint : ∀ i ∈ I, ∀ j ∈ I, i ≠ j → Disjoint (P' i) (P' j) := by
    intro i hi j hj hij
    by_cases hii0 : i = i₀
    · by_cases hji0 : j = i₀
      · exact absurd (hii0.trans hji0.symm) hij
      · simp only [hP'def, if_pos hii0, if_neg hji0]
        have hd : Disjoint (P i₀) (P j) := by rw [← hii0]; exact hP_disj i hi j hj hij
        exact Disjoint.union_left hd (hR_disj_P j hj)
    · by_cases hji0 : j = i₀
      · simp only [hP'def, if_neg hii0, if_pos hji0]
        have hd : Disjoint (P i) (P i₀) := by rw [← hji0]; exact hP_disj i hi j hj hij
        have hr : Disjoint (P i) R := (hR_disj_P i hi).symm
        exact Disjoint.union_right hd hr
      · simp only [hP'def, if_neg hii0, if_neg hji0]
        exact hP_disj i hi j hj hij
  have hP'_cover : (⋃ i ∈ I, P' i) = Set.univ := by
    apply Set.eq_univ_of_forall
    intro n
    by_cases hnI : Equiv (F.restrict (A n)) (succMaxFun 1 h)
    · have hnImem : n ∈ I := hN1_fin.mem_toFinset.mpr hnI
      refine Set.mem_biUnion hnImem ?_
      by_cases hni0 : n = i₀
      · simp only [hP'def, if_pos hni0]
        left
        rw [hni0]
        exact hUmem i₀
      · simp only [hP'def, if_neg hni0]
        exact hUmem n
    · by_cases hnUbig : y n ∈ Ubig
      · obtain ⟨j, hjI, hyj⟩ := Set.mem_iUnion₂.mp hnUbig
        refine Set.mem_biUnion hjI ?_
        by_cases hji0 : j = i₀
        · simp only [hP'def, if_pos hji0]
          left
          rw [← hji0]
          exact hyj
        · simp only [hP'def, if_neg hji0]
          exact hyj
      · refine Set.mem_biUnion hi₀I ?_
        simp only [hP'def, if_pos rfl]
        right
        exact ⟨hnI, hnUbig⟩
  -- For any `i ∈ I` and clopen `V ∋ y i`, `W := V ∪ ⋃_{j ∈ I, j ≠ i} U j` is clopen `⊇ Y₁`.
  -- Since the `U j` are pairwise disjoint, any `n ∈ P i \ {i}` has `y n ∈ W ↔ y n ∈ V`, and such
  -- `n` is automatically in `N₀`. So `hU` (applied to `W`) shows cofinitely many `n ∈ P i \ {i}`
  -- land in `V` — genuine convergence of the *whole* family, not a subsequence. Folding the
  -- (already finite) stragglers `R` into `i`'s own fibre (when `i = i₀`) costs nothing extra.
  have hconv_family' : ∀ i ∈ I, ∀ V : Set Baire, IsClopen V → y i ∈ V →
      {n | n ∈ P' i ∧ n ≠ i ∧ y n ∉ V}.Finite := by
    intro i hi V hVcl hVmem
    set W : Set Baire := V ∪ ⋃ j ∈ I.erase i, U j with hWdef
    have hWcl : IsClopen W := hVcl.union (isClopen_biUnion_finset (fun j _ => hUcl j))
    have hWsub : ∀ n, Equiv (F.restrict (A n)) (succMaxFun 1 h) → y n ∈ W := by
      intro n hn
      rcases eq_or_ne n i with rfl | hne
      · exact Or.inl hVmem
      · exact Or.inr (Set.mem_biUnion
          (Finset.mem_erase.mpr ⟨hne, hN1_fin.mem_toFinset.mpr hn⟩) (hUmem n))
    have hWfin := hU W hWcl hWsub
    have hPi_sub : {n | n ∈ P i ∧ n ≠ i ∧ y n ∉ V} ⊆
        {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∉ W} := by
      rintro n ⟨hnPi, hne, hnV⟩
      have hnI : ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) := by
        intro hnE
        exact (Set.disjoint_left.mp (hdisj n (hN1_fin.mem_toFinset.mpr hnE) i hi hne)
          (hUmem n)) hnPi
      refine ⟨hnI, ?_⟩
      rintro (hnV' | hnU')
      · exact hnV hnV'
      · obtain ⟨j, hj, hyj⟩ := Set.mem_iUnion₂.mp hnU'
        obtain ⟨hjne, hjI⟩ := Finset.mem_erase.mp hj
        exact (Set.disjoint_left.mp (hdisj j hjI i hi hjne) hyj) hnPi
    by_cases hii0 : i = i₀
    · have hsub : {n | n ∈ P' i ∧ n ≠ i ∧ y n ∉ V} ⊆
          {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∉ W} ∪ R := by
        rintro n ⟨hnP'i, hne, hnV⟩
        simp only [hP'def, if_pos hii0, Set.mem_union] at hnP'i
        rcases hnP'i with hnPi | hnR
        · left
          have hnPi' : n ∈ P i := by rw [hii0]; exact hnPi
          exact hPi_sub ⟨hnPi', hne, hnV⟩
        · right; exact hnR
      exact (hWfin.union hL).subset hsub
    · apply Set.Finite.subset hWfin
      intro n hn
      apply hPi_sub
      simpa only [hP'def, if_neg hii0] using hn
  -- `P i₀ \ {i₀}` is infinite, hence so is the folded `P' i₀ \ {i₀}`.
  have hPi0_minus_inf : {n | y n ∈ U i₀ ∧ n ≠ i₀}.Infinite := by
    have heq : {n | y n ∈ U i₀ ∧ n ≠ i₀} = {n | y n ∈ U i₀} \ {i₀} := by
      ext n; simp [Set.mem_diff, and_comm]
    rw [heq]
    exact hPi0_inf.diff (Set.finite_singleton i₀)
  have hP'i0_minus_inf : {n | n ∈ P' i₀ ∧ n ≠ i₀}.Infinite := by
    have hsub : {n | y n ∈ U i₀ ∧ n ≠ i₀} ⊆ {n | n ∈ P' i₀ ∧ n ≠ i₀} := by
      intro n hn
      refine ⟨?_, hn.2⟩
      simp only [hP'def, if_pos rfl, Set.mem_union]
      left; exact hn.1
    exact Set.Infinite.mono hsub hPi0_minus_inf
  set A' : ℕ → Set ↑F.domain := fun i => ⋃ n ∈ P' i, A n with hA'def
  have hA'_eq_of_singleton : ∀ i, P' i = {i} → A' i = A i := by
    intro i hPi
    simp [hA'def, hPi]
  -- case P i = {i}:
  -- F restricted to A' i reduces to Pgl l_λ
  have hreduces_of_singleton : ∀ i ∈ I, P' i = {i} →
      Reduces (F.restrict (A' i)) (succMaxFun 1 h) := by
    intro i hi hPi
    rw [hA'_eq_of_singleton i hPi]
    exact (hN1_fin.mem_toFinset.mp hi).1
  -- Pgl l_λ reduces to F corestricted to U i
  have hreduces_of_singleton_low : ∀ i ∈ I, P' i = {i} →
    Reduces (succMaxFun 1 h) (F.coRestrict (U i)) := by
    intro i hi hPi
    have heq : Equiv (F.restrict (A i)) (succMaxFun 1 h) := hN1_fin.mem_toFinset.mp hi
    have hrank_eq : CBRank (F.restrict (A i)).func = 1 + 1 :=
      (hrank i).trans one_add_one_eq_two.symm
    have hyi_intertwine : y i ∈ IntertwineSet F (succMaxFun 1 h) :=
      succMaxFun_yn_mem_intertwineSet F (A i) 1 h (y i) hrank_eq (hdist i) heq
    have hstep : Reduces (glList (List.replicate ({y i} : Finset Baire).card (succMaxFun 1 h)))
        (F.coRestrict (U i)) := by
      apply glList_replicate_reduces_coRestrict_of_intertwine F (succMaxFun 1 h) (U i) (hUcl i)
        ({y i} : Finset Baire)
      · rw [Finset.coe_singleton]
        exact Set.singleton_subset_iff.mpr (hUmem i)
      · intro p hp
        rw [Finset.mem_singleton] at hp
        rw [hp]
        exact hyi_intertwine
    rw [Finset.card_singleton, List.replicate_one] at hstep
    exact (glList_single_equiv (succMaxFun 1 h)).1.trans hstep
  -- General dichotomy: each `i ∈ I` has either an isolated fibre or an infinite one.
  have hPfin_or_inf : ∀ i ∈ I, P i = {i} ∨ (P i).Infinite := fun i hi =>
    (hiso i hi).imp id (fun h => h K)
  -- `i₀` is never a singleton fibre (it was chosen with an infinite one).
  have hi₀_not_singleton : P i₀ ≠ {i₀} := by
    intro heq
    have hcontra : ({i₀} : Set ℕ).Infinite := heq ▸ hPi0_inf
    exact (Set.finite_singleton i₀).not_infinite hcontra
  -- Any off-`I` block reduces to `minFun 1 h ⊕ maxFun 1 h`.
  have hoffI_reduces : ∀ n, ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) →
      Reduces (F.restrict (A n)) (minFun 1 h ⊕ maxFun 1 h) := by
    intro n hn
    rcases block_classified h F A y n (hrank n) (hdist n) with hc | hc | hc
    · exact hc.1.trans (minFun_one_le_glBin h)
    · exact hc.1
    · exact absurd hc hn
  -- Per-class sandwich: `succMaxFun 1 h` (singleton fibre) or the wedge generator (infinite
  -- fibre, via `diagonal_class_reduces_wedge`), each already known to lie in `FinGl (Generators 2)`.
  have hclass : ∀ i ∈ I, ∃ g : ScatFun, g ∈ FinGl (Generators 2).toFinFun ∧
      Reduces (F.restrict (A' i)) g ∧ Reduces g (F.coRestrict (U i)) := by
    intro i hi
    rcases hPfin_or_inf i hi with hsing | hinf
    · have hP'sing : P' i = {i} := by
        by_cases hii0 : i = i₀
        · exact absurd (by rw [← hii0]; exact hsing) hi₀_not_singleton
        · simpa only [hP'def, if_neg hii0] using hsing
      exact ⟨succMaxFun 1 h, succMaxFun_one_mem_finGl_two h,
        hreduces_of_singleton i hi hP'sing, hreduces_of_singleton_low i hi hP'sing⟩
    · set S : Set ℕ := {n | n ∈ P' i ∧ n ≠ i} with hSdef
      have hiP' : i ∈ P' i := by
        by_cases hii0 : i = i₀
        · simp only [hP'def, if_pos hii0, Set.mem_union]
          left
          rw [hii0]
          exact hUmem i₀
        · simp only [hP'def, if_neg hii0]
          exact hUmem i
      have hSinf : S.Infinite := by
        by_cases hii0 : i = i₀
        · have hSeq : S = {n | n ∈ P' i₀ ∧ n ≠ i₀} := by rw [hSdef, hii0]
          rw [hSeq]
          exact hP'i0_minus_inf
        · have hP'eq : P' i = P i := by simp only [hP'def, if_neg hii0]
          have hSeq : S = P i \ {i} := by
            rw [hSdef, hP'eq]; ext n; simp [Set.mem_diff, and_comm]
          rw [hSeq]
          exact hinf.diff (Set.finite_singleton i)
      have h0 : Equiv (F.restrict (A i)) (succMaxFun 1 h) := hN1_fin.mem_toFinset.mp hi
      have hiS : i ∉ S := fun hmem => hmem.2 rfl
      have hSclass : ∀ n ∈ S, Reduces (F.restrict (A n)) (minFun 1 h ⊕ maxFun 1 h) := by
        intro n hn
        obtain ⟨hnP', hne⟩ := hn
        apply hoffI_reduces
        intro hnE
        have hnI : n ∈ I := hN1_fin.mem_toFinset.mpr hnE
        by_cases hii0 : i = i₀
        · simp only [hP'def, if_pos hii0, Set.mem_union] at hnP'
          rcases hnP' with hnP | hnR
          · exact (Set.disjoint_left.mp
              (hdisj n hnI i₀ hi₀I (by rw [← hii0]; exact hne)) (hUmem n)) hnP
          · exact hnR.1 hnE
        · simp only [hP'def, if_neg hii0] at hnP'
          exact (Set.disjoint_left.mp (hdisj n hnI i hi hne) (hUmem n)) hnP'
      have hSconv : ∀ V : Set Baire, IsClopen V → y i ∈ V → {n | n ∈ S ∧ y n ∉ V}.Finite := by
        intro V hVcl hVmem
        have hSVeq : {n | n ∈ S ∧ y n ∉ V} = {n | n ∈ P' i ∧ n ≠ i ∧ y n ∉ V} := by
          ext n; simp [hSdef, and_assoc]
        rw [hSVeq]
        exact hconv_family' i hi V hVcl hVmem
      have hdiag := diagonal_class_reduces_wedge 1 h F A hdu y hy_inj
        (fun n => (hrank n).trans one_add_one_eq_two.symm) hdist i h0
        S hiS hSinf hSclass hSconv (U i) (hUcl i) (hUmem i)
      have hA'eq : A' i = A i ∪ ⋃ n ∈ S, A n := by
        rw [hA'def]
        apply Set.Subset.antisymm
        · rintro x hx
          obtain ⟨n, hnmem, hxn⟩ := Set.mem_iUnion₂.mp hx
          by_cases hni : n = i
          · exact Or.inl (hni ▸ hxn)
          · exact Or.inr (Set.mem_biUnion (show n ∈ S from ⟨hnmem, hni⟩) hxn)
        · rintro x (hx | hx)
          · exact Set.mem_biUnion hiP' hx
          · obtain ⟨n, hnS, hxn⟩ := Set.mem_iUnion₂.mp hx
            exact Set.mem_biUnion hnS.1 hxn
      refine ⟨wedge (fun _ : Fin 1 => maxFun 1 h) (minFun 1 h),
        wedge_maxFun_minFun_one_mem_finGl_two h, ?_, hdiag.2⟩
      rw [hA'eq]
      exact hdiag.1
  -- Assemble via the finite fibre-family lemma.
  choose g hgmem hgup hglow using hclass
  have ht_mem : ∀ n, ∃ i, i ∈ I ∧ n ∈ P' i := by
    intro n
    have hn : n ∈ ⋃ i ∈ I, P' i := by rw [hP'_cover]; exact Set.mem_univ n
    simpa using Set.mem_iUnion₂.mp hn
  choose t htI htP' using ht_mem
  set A'' : ℕ → Set ↑F.domain := fun i => ⋃ k ∈ {k | t k = i}, A k with hA''def
  have hdu'' : F.IsDisjointUnion A'' := ScatFun.IsDisjointUnion.regroup F A hdu t
  have hA''_eq : ∀ i ∈ I, A'' i = A' i := by
    intro i hi
    rw [hA''def, hA'def]
    apply Set.Subset.antisymm
    · rintro x hx
      obtain ⟨k, hk, hxk⟩ := Set.mem_iUnion₂.mp hx
      have hk' : t k = i := hk
      refine Set.mem_biUnion ?_ hxk
      rw [← hk']
      exact htP' k
    · rintro x hx
      obtain ⟨n, hnP', hxn⟩ := Set.mem_iUnion₂.mp hx
      have htn : t n = i := by
        by_contra hne
        exact (Set.disjoint_left.mp
          (hP'_pairwiseDisjoint (t n) (htI n) i hi hne) (htP' n)) hnP'
      exact Set.mem_biUnion htn hxn
  have hA''_empty : ∀ n, n ∉ I → A'' n = ∅ := by
    intro n hn
    rw [hA''def]
    apply Set.eq_empty_iff_forall_notMem.mpr
    intro x hx
    obtain ⟨k, hk, _⟩ := Set.mem_iUnion₂.mp hx
    have hk' : t k = n := hk
    exact hn (by rw [← hk']; exact htI k)
  set U'' : ℕ → Set Baire := fun i => if i ∈ I then U i else ∅ with hU''def
  have hU''cl : ∀ i, IsClopen (U'' i) := by
    intro i
    by_cases hi : i ∈ I
    · simp only [hU''def, if_pos hi]
      exact hUcl i
    · simp only [hU''def, if_neg hi]
      exact isClopen_empty
  have hU''disj : Pairwise (Disjoint on U'') := by
    intro i j hij
    by_cases hi : i ∈ I
    · by_cases hj : j ∈ I
      · simp only [Function.onFun, hU''def, if_pos hi, if_pos hj]
        exact hdisj i hi j hj hij
      · simp [Function.onFun, hU''def, if_pos hi, if_neg hj]
    · simp [Function.onFun, hU''def, if_neg hi]
  -- `g` from `choose` depends on the membership proof `hi : i ∈ I`; package it into a plain
  -- `ℕ → ScatFun` (arbitrary value off `I`) for `finGl_sandwich`.
  set g' : ℕ → ScatFun := fun i => if hi : i ∈ I then g i hi else succMaxFun 1 h with hg'def
  apply finGl_sandwich F I A'' hdu'' hA''_empty U'' hU''cl hU''disj g'
  · intro i hi
    rw [hA''_eq i hi]
    have hg'eq : g' i = g i hi := by simp only [hg'def, dif_pos hi]
    rw [hg'eq]
    exact hgup i hi
  · intro i hi
    have hUeq : U'' i = U i := by simp only [hU''def, if_pos hi]
    have hg'eq : g' i = g i hi := by simp only [hg'def, dif_pos hi]
    rw [hUeq, hg'eq]
    exact hglow i hi
  · intro i hi
    have hg'eq : g' i = g i hi := by simp only [hg'def, dif_pos hi]
    rw [hg'eq]
    exact hgmem i hi



theorem case_N1_finite_nonempty_two (h : (1 : Ordinal.{0}) < omega1)
    (F : ScatFun) (A : ℕ → Set ↑F.domain) (hdu : F.IsDisjointUnion A)
    (y : ℕ → Baire) (hy_inj : Function.Injective y)
    (hrank : ∀ n, CBRank (F.restrict (A n)).func = 2)
    (hdist : ∀ n, ∀ x ∈ CBLevel (F.restrict (A n)).func 1, (F.restrict (A n)).func x = y n)
    (hN1_fin : {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}.Finite)
    (hN1_ne : {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}.Nonempty) :
    F ∈ FinGl (Generators 2).toFinFun := by
  by_cases hcase : ∃ U : Set Baire, IsClopen U ∧
      (∀ n, Equiv (F.restrict (A n)) (succMaxFun 1 h) → y n ∈ U) ∧
      {n | ¬ Equiv (F.restrict (A n)) (succMaxFun 1 h) ∧ y n ∉ U}.Infinite
  · exact case_N1_finite_nonempty_subcase_a_two h F A hdu y hy_inj hrank hdist hN1_fin hN1_ne hcase
  · refine case_N1_finite_nonempty_subcase_b_two h F A hdu y hy_inj hrank hdist hN1_fin hN1_ne ?_
    push_neg at hcase
    intro U hUcl hUsub
    exact hcase U hUcl hUsub

/-- **`CB`-rank-`2` functions with *infinite* `CB`-degree are finitely generated** — the
complementary case to `Generators_two_finitely_generates_of_finite_degree`, together covering
all of `5_precise_struct_memo.tex:385-422` at `λ = 1`.

## Provided solution

Decompose `F` into simple blocks `Fₙ = F.restrict (A n)` of rank `2` with pairwise distinct
distinguished points `(y n)` (the Decomposition Lemma step described above the three case
theorems). Classify each block via `simpleFunctionsLambdaPlusOne` at `lam = 1` (fed
`twoBQO_levelLT_one`, as already noted for the finite-degree theorem above). Set
`N₁ := {n | Equiv (F.restrict (A n)) (succMaxFun 1 h)}` and dispatch on `Set.Infinite N₁ ∨
N₁ = ∅ ∨ (N₁.Finite ∧ N₁.Nonempty)` (`Set.eq_empty_or_nonempty` + `Set.finite_or_infinite`) to
`case_N1_infinite_two`, `case_N1_empty_two`, or `case_N1_finite_nonempty_two` respectively. -/
theorem Generators_two_finitely_generates_of_infinite_degree :
    ∀ F : ScatFun, CBRank F.func = 2 → (F.func '' CBLevel F.func 1).Infinite →
      F ∈ FinGl (Generators 2).toFinFun := by
  intro F hF hinf
  have h1 : (1 : Ordinal.{0}) < omega1 := one_lt_omega1
  have h2 : (2 : Ordinal.{0}) < omega1 := by
    have hle : Ordinal.omega0 ≤ omega1 := by
      have := Cardinal.ord_le_ord.mpr (Cardinal.aleph0_le_aleph 1)
      rwa [Cardinal.ord_aleph0] at this
    exact lt_of_lt_of_le (by exact_mod_cast Ordinal.nat_lt_omega0 2) hle
  have hF' : CBRank F.func = 1 + 1 := by rw [hF]; exact one_add_one_eq_two.symm
  obtain ⟨A, y, hdu, hy_inj, hrank1, hdist1⟩ :=
    exists_simple_block_decomposition 1 F hF' hinf
  have hrank : ∀ n, CBRank (F.restrict (A n)).func = 2 :=
    fun n => (hrank1 n).trans one_add_one_eq_two
  rcases Set.finite_or_infinite {n | Equiv (F.restrict (A n)) (succMaxFun 1 h1)} with
    hfin | hinf'
  · rcases Set.eq_empty_or_nonempty {n | Equiv (F.restrict (A n)) (succMaxFun 1 h1)} with
      hempty | hne
    · exact case_N1_empty_two h1 F A hdu y hy_inj hrank hdist1 hempty
    · exact case_N1_finite_nonempty_two h1 F A hdu y hy_inj hrank hdist1 hfin hne
  · exact case_N1_infinite_two h1 h2 F A hdu y hy_inj hrank hdist1 hinf'

/-
**Level `2` is finitely generated by `𝒢_2`.**  The `λ = 1` instance of
`FGatsuccessoroflimit` (`5_precise_struct_memo.tex:377-423`), combining the finite- and
infinite-`CB`-degree cases.

## Provided solution

By `finitedegreedamuddafuckaz` (`4_centered_memo.tex:372`), split on whether the last `CB`-level's
image `F.func '' CBLevel F.func 1` is finite or infinite (`Set.finite_or_infinite`) and dispatch
to `Generators_two_finitely_generates_of_finite_degree` or
`Generators_two_finitely_generates_of_infinite_degree` respectively.
-/
theorem Generators_two_finitely_generates :
    ∀ F : ScatFun, CBRank F.func = 2 → F ∈ FinGl (Generators 2).toFinFun := by
  intro F h
  rcases (F.func '' CBLevel F.func 1).finite_or_infinite with hfin | hinf
  · exact Generators_two_finitely_generates_of_finite_degree F h hfin
  · exact Generators_two_finitely_generates_of_infinite_degree F h hinf

end ScatFun

end
